<a href="https://colab.research.google.com/github/adilkamal2478/Adil_Pandas_Data_Preprocessing/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [5]:
df = pd.read_excel("/content/drive/MyDrive/Data_processing/smartprix-phones-table.xlsx", engine="openpyxl")

In [6]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,Apple iPhone 18 Pro,"₹1,64,900",85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,Vivo T4 Pro 5G (8GB RAM + 256GB),"₹29,999",72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,Apple iPhone Duo,"₹2,99,900",84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,Apple iPhone 18 Pro Max,"₹1,79,900",86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,Realme P1 5G (8GB RAM+ 128GB),"₹14,999",58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14
...,...,...,...,...,...,...,...,...,...,...,...
1014,Foneme FM-1 Vibe 30C,₹799,NaN,Dual Sim,"Single Core, 1.77 MHz Processor","8 MB RAM, 16 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,Symbian v60,Bluetooth
1015,Snexian Guru 219C,₹749,NaN,Dual Sim,1.41 MHz Processor,16 MB RAM,1000 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v30,Bluetooth
1016,Snexian Rock X Flip,"₹1,799",NaN,Dual Sim,"Unisoc, Single Core, 1 MHz Processor","32 MB RAM, 32 MB inbuilt",1500 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v0,No FM Radio
1017,Snexian Guru 220C,₹749,NaN,Dual Sim,1.41 MHz Processor,"16 MB RAM, 128 MB inbuilt",1000 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v30,Bluetooth
1018,MTR M115,"₹1,050",NaN,Dual Sim,128 MHz Processor,"32 MB RAM, 32 MB inbuilt",1100 mAh Battery,"1.44 inches, 120 x 240 px Display",0.03 MP Rear Camera,Memory Card Supported,No FM Radio

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** -  
5. **ratings** - missing values `completeness`
6. **processor** - 619 , 880
7.
8. **memory** - incorrect values in rows (284,501,880) `validity`
9. **battery** - incorrect values in rows(880) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(880) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (4,26,43,103,136,145,147,266,274,306,311,327,405,435,452,467,468,484,520,539,551,560,606,619,630,654,663,673,674,675,678,691,726,743,744,755,756,766,771,796,802,812,825,880,936,1007
)- 714,900,902,1015 missings `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [7]:
df1 = df.copy()

In [8]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [20]:
df1 = df1.reset_index()

In [21]:
df1['index'] = df1['index'] + 2

In [22]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,5,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [25]:
df1 = df1[df1['price'] > 4999]

In [26]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,5,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14
...,...,...,...,...,...,...,...,...,...,...,...,...
998,1000,OnePlus 7 (8GB RAM + 256GB),33999,57.0,"Dual Sim, 4G, VoLTE, NFC, Wi-Fi","Snapdragon 855, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 20W Fast Charging,"6.41 inches, 1080 x 2340 px Display with Water...",48 MP + 5 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v9.0 (Pie)
999,1001,Xiaomi Redmi Note 7 Pro (6GB RAM + 128GB),15999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 675, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.3 inches, 1080 x 2340 px Display with Water ...",48 MP + 5 MP Dual Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v9.0 (Pie)
1000,1002,Realme 2 (3GB RAM + 32GB),9990,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.2 inches, 720 x 1520 px Display with Small N...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1011,1013,Lava Yuva Star 3,12499,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","UNISOC 9863a, Octa Core Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px, 90 Hz Display with...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v15