<a href="https://colab.research.google.com/github/adilkamal2478/Adil_Pandas_Data_Preprocessing/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [4]:
df = pd.read_excel("/content/drive/MyDrive/Data_processing/smartprix-phones-table.xlsx", engine="openpyxl")

In [5]:
df

,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,Apple iPhone 18 Pro,"₹1,64,900",85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,Vivo T4 Pro 5G (8GB RAM + 256GB),"₹29,999",72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,Apple iPhone Duo,"₹2,99,900",84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,Apple iPhone 18 Pro Max,"₹1,79,900",86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,Realme P1 5G (8GB RAM+ 128GB),"₹14,999",58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14
...,...,...,...,...,...,...,...,...,...,...,...
1014,Foneme FM-1 Vibe 30C,₹799,NaN,Dual Sim,"Single Core, 1.77 MHz Processor","8 MB RAM, 16 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",0.3 MP Rear Camera,Symbian v60,Bluetooth
1015,Snexian Guru 219C,₹749,NaN,Dual Sim,1.41 MHz Processor,16 MB RAM,1000 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v30,Bluetooth
1016,Snexian Rock X Flip,"₹1,799",NaN,Dual Sim,"Unisoc, Single Core, 1 MHz Processor","32 MB RAM, 32 MB inbuilt",1500 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v0,No FM Radio
1017,Snexian Guru 220C,₹749,NaN,Dual Sim,1.41 MHz Processor,"16 MB RAM, 128 MB inbuilt",1000 mAh Battery,"1.8 inches, 120 x 240 px Display",0.3 MP Rear Camera,Symbian v30,Bluetooth
1018,MTR M115,"₹1,050",NaN,Dual Sim,128 MHz Processor,"32 MB RAM, 32 MB inbuilt",1100 mAh Battery,"1.44 inches, 120 x 240 px Display",0.03 MP Rear Camera,Memory Card Supported,No FM Radio

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** -  
5. **ratings** - missing values `completeness`
6. **processor** - 619 , 880
7.
8. **memory** - incorrect values in rows (284,501,880) `validity`
9. **battery** - incorrect values in rows(880) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(880) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (4,26,43,103,136,145,147,266,274,306,311,327,405,435,452,467,468,484,520,539,551,560,606,619,630,654,663,673,674,675,678,691,726,743,744,755,756,766,771,796,802,812,825,880,936,1007
)- 714,900,902,1015 missings `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [6]:
df1 = df.copy()

In [7]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [8]:
df1 = df1.reset_index()

In [9]:
df1['index'] = df1['index'] + 2

In [10]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,5,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [11]:
df1 = df1[df1['price'] > 4999]

In [12]:
df1

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,5,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14
...,...,...,...,...,...,...,...,...,...,...,...,...
998,1000,OnePlus 7 (8GB RAM + 256GB),33999,57.0,"Dual Sim, 4G, VoLTE, NFC, Wi-Fi","Snapdragon 855, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 20W Fast Charging,"6.41 inches, 1080 x 2340 px Display with Water...",48 MP + 5 MP Dual Rear & 16 MP Front Camera,Memory Card Not Supported,Android v9.0 (Pie)
999,1001,Xiaomi Redmi Note 7 Pro (6GB RAM + 128GB),15999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 675, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.3 inches, 1080 x 2340 px Display with Water ...",48 MP + 5 MP Dual Rear & 13 MP Front Camera,"Memory Card (Hybrid), upto 256 GB",Android v9.0 (Pie)
1000,1002,Realme 2 (3GB RAM + 32GB),9990,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Snapdragon 450, Octa Core, 1.8 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.2 inches, 720 x 1520 px Display with Small N...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v8.1 (Oreo)
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
1011,1013,Lava Yuva Star 3,12499,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","UNISOC 9863a, Octa Core Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.75 inches, 720 x 1600 px, 90 Hz Display with...",13 MP Dual Rear & 5 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v15

In [14]:
processor_rows = set((619 , 880))
ram_rows = set((284,501,880))
battery_rows = set((880,))
display_rows = set((880,))
camera_rows = set((4,26,43,103,136,145,147,266,274,306,311,327,405,435,452,467,468,484,520,539,551,560,606,619,630,654,663,673,674,675,678,691,726,743,744,755,756,766,771,796,802,812,825,880,936,1007))

In [17]:
df1[df1['index'].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
282,284,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
499,501,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0,No FM Radio,Bluetooth
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [59]:
temp_df = df1[df1['index'].isin(processor_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0,No FM Radio,Bluetooth
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth

In [60]:
# processor_row
# 619 rows
temp_df.iloc[0, 7:] = temp_df.iloc[0, 5:-2].values

In [61]:
temp_df.iloc[0, 5:7] = None

In [62]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth

In [63]:
# row 880
temp_df.iloc[1,6:] = temp_df.iloc[1,5:-1]

In [64]:
temp_df.iloc[1, (5,10,11)] = None

In [65]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None

In [77]:
df1[df1['index'].isin([619, 880])] = temp_df

In [79]:
# ram rows

df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
282,284,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
499,501,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None

In [ ]:
# battery row
# display row

# already fixed

In [104]:
# camera

temp_df = df1[df1['index'].isin(camera_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [105]:
temp_df.shape
mask = ~temp_df['index'].isin([619, 880])

temp_df.loc[mask, temp_df.columns[9]] = temp_df.loc[mask, temp_df.columns[10]]

In [106]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [110]:
df1[df1['index'].isin(camera_rows)] = temp_df

In [117]:
# see all rows in pandas

pd.set_option('display.max_rows', None)

# pd.reset_option('display.max_rows')

In [122]:
# card row

temp_df = df1[df1['card'].str.contains('Android' , na=False)]
temp_df['card'].value_counts()

card
Android v15      79
Android v16      69
Android v14      30
Android v12      19
Android v13      10
Android v17       7
Android v11       4
Android v10       4
Android           2
Android v12.0     2
Android v13.0     1
Android v14.0     1
Name: count, dtype: int64

In [124]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
5,7,Motorola Edge 70 Fusion,27695,70.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
9,11,Poco X7 Pro 5G,23999,70.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
12,14,OnePlus Nord 5 5G,33999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
15,17,Realme P3 5G,15999,61.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
20,22,Oppo K13 (8GB RAM + 256GB),23999,63.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
22,24,Motorola Edge 70 Pro,39849,83.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8500 Extreme, Octa Core, 3.4 GHz Pro...","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
26,28,OPPO Reno 14 5G,44999,76.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8350, Octa Core, 3.35 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front...,Android v15,No FM Radio
28,30,Realme P4 Pro 5G,28999,71.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7 Gen 4, Octa Core Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
32,34,Motorola Edge 60 Pro,30190,76.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
39,41,Nothing Phone 2a (8GB RAM + 256GB),24999,70.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7200 Pro, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1084 x 2412 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 32 MP Front Camera,Android v14,No FM Radio
42,44,Poco X7 5G,17999,64.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
43,45,Motorola Edge 70 5G,32490,75.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 68W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
49,51,Samsung Galaxy S25 5G,66000,77.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite, Octa Core, 4.47 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
51,53,Realme P3 5G (8GB RAM + 128GB),16999,63.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
54,56,Realme P3 Pro 5G (12GB RAM +256GB),23999,66.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
60,62,Motorola Signature,59899,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",5200 mAh Battery with 90W Fast Charging,"6.8 inches, 1264 x 2780 px, 165 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
61,63,Samsung Galaxy A36 5G,28000,64.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen3, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
65,67,Poco X7 5G (8GB RAM + 256GB),19999,66.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi, IR Blaster","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 256 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
67,69,Realme P4x 5G,21939,62.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","6 GB RAM, 128 GB inbuilt",7000 mAh Battery with 45W Fast Charging,"6.72 inches, 1080 x 2400 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v15,No FM Radio
74,76,Google Pixel 11,82300,74.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",Tensor G6,"12 GB RAM, 256 GB inbuilt",4985 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Android v17,No FM Radio
76,78,Oppo F31 Pro 5G,25999,66.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7300 Energy, Octa Core, 2.5 GHz Proc...","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.57 inches, 1080 x 2372 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
77,79,Poco X7 Pro (12GB RAM + 256GB),25999,71.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","12 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
82,84,Realme 15 Pro 5G (12GB RAM + 256GB),33499,76.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
85,87,iQOO Z11xA 5G,28999,64.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7400 Turbo, Octa Core, 2.6 GHz Proce...","8 GB RAM, 128 GB inbuilt",7200 mAh Battery with 44W Fast Charging,"6.76 inches, 1080 x 2344 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
87,89,Samsung Galaxy S26 5G,79999,80.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.3 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v16,No FM Radio
88,90,Samsung Galaxy A56 5G,34999,63.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Exynos 1580, Octa Core, 2.9 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front...,Android v15,No FM Radio
89,91,OPPO Reno 14 Pro 5G,49890,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi, IR Blaster","Dimensity 8450, Octa Core, 3.25 GHz Processor","12 GB RAM, 256 GB inbuilt",6200 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
92,94,Samsung Galaxy S24 5G (Snapdragon),49999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.2 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v15,No FM Radio
96,98,Xiaomi Redmi Note 17 5G,27999,61.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 4 Gen4, Octa Core, 2.3 GHz Processor","6 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.99 inches, 1080 x 2396 px, 120 Hz Display wi...",50 MP Rear & 8 MP Front Camera,Android v16,No FM Radio
97,99,OnePlus Nord CE 6 5G,37999,74.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",8000 mAh Battery with 80W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
98,100,Motorola Edge 70 Fusion 5G (8GB RAM + 256 GB),35884,71.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
104,106,Oppo Find X9 5G,84999,89.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 9500, Octa Core, 4.21 GHz Processor","12 GB RAM, 256 GB inbuilt",7025 mAh Battery with 80W Fast Charging,"6.59 inches, 1256 x 2760 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v16,No FM Radio
105,107,iQOO 15,76999,94.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Elite Gen 5, Octa Core, 4.6 GHz P...","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 100W Fast Charging,"6.85 inches, 1440 x 3168 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP Fron...,Android v16,No FM Radio
107,109,Xiaomi Redmi Note 15 Pro 5G,31999,72.0,"Dual Sim, 5G, VoLTE, eSIM, Wi-Fi, IR Blaster","Dimensity 7400 Ultra, Octa Core, 2.6 GHz Proce...","8 GB RAM, 128 GB inbuilt",6580 mAh Battery with 45W Fast Charging,"6.83 inches, 1280 x 2772 px, 120 Hz Display wi...",200 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
110,112,OPPO K13,21999,62.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
114,116,Xiaomi Redmi Note 14 Pro 5G,21999,62.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 7300 Ultra, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 45W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front ...,Android v14,No FM Radio
116,118,Motorola Edge 70 Fusion 5G (12GB RAM + 256 GB),34980,72.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","12 GB RAM, 256 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
117,119,Google Pixel 10 5G,67340,75.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","12 GB RAM, 256 GB inbuilt",4970 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2424 px, 120 Hz Display wit...",48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP ...,Android v16,No FM Radio
120,122,Nothing Phone 3 (16GB RAM + 512GB),51999,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",5500 mAh Battery with 65W Fast Charging,"6.67 inches, 1260 x 2800 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
121,123,Nothing Phone 4a,35799,71.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",5400 mAh Battery with 50W Fast Charging,"6.78 inches, 1224 x 2720 px, 120 Hz Display wi...",50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front...,Android v16,No FM Radio
122,124,OnePlus Nord 4 5G (8GB RAM + 256GB),29999,70.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 7+ Gen3, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",5500 mAh Battery with 100W Fast Charging,"6.74 inches, 1240 x 2772 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Android v14,No FM Radio
123,125,Motorola Moto G67 Power 5G,22949,62.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 30W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
125,127,iQOO 15R,53999,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7600 mAh Battery with 100W Fast Charging,"6.59 inches, 1260 x 2750 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v16,No FM Radio
126,128,Realme P1 Pro 5G (8GB RAM + 256GB),16999,59.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 6 Gen1, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 16 MP Front Camera,Android v14,No FM Radio
128,130,Moto G57 Power,20999,57.0,"Dual Sim, 5G, eSIM, Wi-Fi","Snapdragon 6s Gen4, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 33W Fast Charging,"6.72 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Android v16,Bluetooth
129,131,Realme P4R 5G,19890,57.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.81 inches, 720 x 1570 px, 144 Hz Display wit...",50 MP Rear & 8 MP Front Camera,Android v16,No FM Radio
135,137,Poco X8 Pro 5G,39690,76.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8500 Ultra, Octa Core, 3.4 GHz Proce...","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 100W Fast Charging,"6.59 inches, 2756 x 1268 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
137,139,Motorola Edge 50 5G,22990,70.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7 Gen1 AE, Octa Core, 2.5 GHz Proce...","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 68W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display",50 MP + 13 MP + 10 MP Triple Rear & 32 MP Fron...,Android v14,No FM Radio
139,141,Samsung Galaxy S25 Edge,60800,80.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite, Octa Core, 4.47 GHz Processor","12 GB RAM, 256 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP + 12 MP Dual Rear & 12 MP Front Camera,Android v15,No FM Radio
144,146,Realme P3 Pro 5G (8GB RAM +256GB),21999,64.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
148,150,iQOO Neo 10 (8GB RAM + 256GB),43999,80.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen4, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 120W Fast Charging,"6.78 inches, 1260 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v15,No FM Radio
149,151,Motorola Edge 70 Pro Plus 5G,48780,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8500 Extreme, Octa Core, 3.4 GHz Pro...","12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.78 inches, 1272 x 2772 px, 144 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Android v16,No FM Radio
165,167,Google Pixel 11 Pro,119999,85.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",Tensor G6,"12 GB RAM, 256 GB inbuilt",4850 mAh Battery with Fast Charging,"6.3 inches, 1280 x 2856 px, 120 Hz Display wit...",50 MP + 48 MP + 48 MP Triple Rear & 42 MP Fron...,Android v17,No FM Radio
170,172,Xiaomi Redmi Turbo 5,41999,76.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8500 Ultra, Octa Core, 3.4 GHz Proce...","8 GB RAM, 256 GB inbuilt",7540 mAh Battery with 100W Fast Charging,"6.59 inches, 1268 x 2756 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
172,174,Realme P2 Pro 5G,17999,63.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen 2, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",5200 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v14,No FM Radio
173,175,Motorola Edge 70 Pro 5G (12GB RAM + 256GB),42865,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8500 Extreme, Octa Core, 3.4 GHz Pro...","12 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 50 MP Dual Rear & 50 MP Front Camera,Android v16,No FM Radio
177,179,Motorola Edge 60 Pro (12GB RAM + 256GB),35385,77.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Dimensity 8350 Extreme, Octa Core, 3.35 GHz Pr...","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 90W Fast Charging,"6.7 inches, 1220 x 2712 px, 120 Hz Display wit...",50 MP + 50 MP + 10 MP Triple Rear & 50 MP Fron...,Android v15,No FM Radio
191,193,Tecno Pova Slim 5G,20999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 6400, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.78 inches, 1224 x 2720 px, 144 Hz Display wi...",50 MP + 2 MP Dual Rear & 13 MP Front Camera,Android v15,No FM Radio
196,198,Samsung Galaxy M56 5G,31999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Exynos 1480, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.74 inches, 1080 x 2340 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front ...,Android v15,No FM Radio
197,199,Realme P3 Pro 5G,20999,63.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 7s Gen3, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
199,201,Poco X8 Pro Max,48999,83.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 9500s, Octa Core, 3.73 GHz Processor","12 GB RAM, 256 GB inbuilt",9000 mAh Battery with 100W Fast Charging,"6.83 inches, 1280 x 2772 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v16,No FM Radio
200,202,Realme P4 Pro 5G (8GB RAM + 256GB),30999,72.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 7 Gen 4, Octa Core Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.8 inches, 1280 x 2800 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio

In [129]:
temp_df.iloc[:, 11] = temp_df.iloc[:, 10].values

In [131]:
temp_df.iloc[:, 10] = "Memory Card Not Supported"

In [133]:
df1[df1['card'].str.contains('Android' , na=False)] = temp_df

In [140]:
temp_df = df1[df1['card'].str.contains('MP' , na=False)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
913,915,Google Pixel 9 Pro Fold,132900,85.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [142]:
temp_df.iloc[:, 10] = "Memory Card Not Supported"

In [144]:
df1[df1['card'].str.contains('MP' , na=False)] = temp_df

In [146]:
df1['card'].value_counts()

card
Memory Card Not Supported             480
Memory Card (Hybrid), upto 1 TB       101
Memory Card Supported, upto 1 TB       78
Memory Card (Hybrid), upto 2 TB        75
Memory Card (Hybrid)                   64
Memory Card Supported                  42
Memory Card Supported, upto 2 TB       36
Memory Card Supported, upto 256 GB     13
Memory Card Supported, upto 512 GB     10
Memory Card (Hybrid), upto 1.5 TB       7
Memory Card (Hybrid), upto 128 GB       5
Memory Card (Hybrid), upto 256 GB       4
Memory Card Supported, upto 128 GB      3
Memory Card (Hybrid), upto 512 GB       2
Name: count, dtype: int64

In [152]:
df1['os'].value_counts()

os
Android v16                  284
Android v15                  256
Android v14                  107
Android v12                   58
Android v13                   53
Android v11                   39
Memory Card Not Supported     24
Android v17                   16
Android v10                   11
iOS v26                       11
iOS v27                        8
Android v9.0 (Pie)             8
iOS v18                        7
iOS v17                        5
Android v10.0                  5
No FM Radio                    3
Android v8.1 (Oreo)            3
iOS v26.3                      2
v60                            2
Android                        2
Android 15 Go                  2
Android v12.0                  2
Android v14.0                  2
Android 15 Go Edition          2
v30                            1
iOS v15                        1
Android v13.0                  1
Memory Card (Hybrid)           1
Bluetooth                      1
iOS v11                        1
Name: count, dtype: int64

In [153]:
temp_df = df1[~df1['os'].str.contains('Android|iOS' , case=False,na=False)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
5,7,Motorola Edge 70 Fusion,27695,70.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Memory Card Not Supported,None
9,11,Poco X7 Pro 5G,23999,70.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Memory Card Not Supported,None
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
333,335,Ringme Bold S170 Air Pro,13000,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Dual Core, 1.7 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.61 inches, 128 x 160 px Display with Punch Hole",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",v30
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Memory Card (Hybrid)
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
710,712,Peace i Ultra,10999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",Single Core Processor,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.61 inches, 720 x 1640 px Display with Punch ...",20 MP Rear & 8 MP Front Camera,Memory Card Supported,v60
722,724,Peace Nova 17 Pro 4G (6GB RAM + 64GB),9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
793,795,Ringme Bold 16 Pro,9899,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",Dual Core Processor,"4 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.61 inches, 128 x 160 px Display",13 MP Rear Camera,"Memory Card (Hybrid), upto 128 GB",Bluetooth
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
808,810,Peace Nova 17 Pro 4G (6GB RAM + 128GB),9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
870,872,Peace Nova 13,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Single Core, 1.7 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.85 inches, 1640 x 720 px Display with Punch ...",20 MP Rear Camera,"Memory Card Supported, upto 128 GB",v60
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
888,890,Peace Nova 17 Pro 4G,9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported

In [156]:
temp_df.iloc[:,11] = None

In [159]:
df1[~df1['os'].str.contains('Android|iOS' , case=False,na=False)] = temp_df

In [162]:
df1['os'].value_counts()

os
Android v16              284
Android v15              256
Android v14              107
Android v12               58
Android v13               53
Android v11               39
Android v17               16
iOS v26                   11
Android v10               11
Android v9.0 (Pie)         8
iOS v27                    8
iOS v18                    7
iOS v17                    5
Android v10.0              5
Android v8.1 (Oreo)        3
Android v12.0              2
Android                    2
Android 15 Go              2
iOS v26.3                  2
Android v14.0              2
Android 15 Go Edition      2
iOS v15                    1
Android v13.0              1
iOS v11                    1
Name: count, dtype: int64

In [163]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 921 entries, 0 to 1011
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      921 non-null    int64
 1   model      921 non-null    object
 2   price      921 non-null    int64
 3   rating     786 non-null    float64
 4   sim        921 non-null    object
 5   processor  919 non-null    object
 6   ram        920 non-null    object
 7   battery    921 non-null    object
 8   display    921 non-null    object
 9   camera     921 non-null    object
 10  card       920 non-null    object
 11  os         886 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 125.8+ KB

In [172]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera                                           58
50 MP + 2 MP Dual Rear & 16 MP Front Camera                                          34
50 MP + 8 MP Dual Rear & 32 MP Front Camera                                          33
50 MP Dual Rear & 8 MP Front Camera                                                  31
50 MP + 8 MP Dual Rear & 16 MP Front Camera                                          27
50 MP Rear & 8 MP Front Camera                                                       26
50 MP + 2 MP Dual Rear & 32 MP Front Camera                                          25
13 MP Rear & 5 MP Front Camera                                                       23
50 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                                22
50 MP + 5 MP + 2 MP Triple Rear & 13 MP Front Camera                                 15
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                               15
48 MP + 48 MP + 48 MP Triple Rear & 18 MP Front Camera                               14
50 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                               13
50 MP + 2 MP Dual Rear & 5 MP Front Camera                                           13
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                                 13
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                               12
50 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                                12
8 MP Rear & 5 MP Front Camera                                                        12
13 MP Dual Rear & 5 MP Front Camera                                                  12
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                 12
50 MP + 8 MP Dual Rear & 20 MP Front Camera                                          11
50 MP + 2 MP Dual Rear & 50 MP Front Camera                                          11
200 MP Quad Rear & 12 MP Front Camera                                                10
13 MP Rear & 8 MP Front Camera                                                       10
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                                 10
50 MP + 8 MP Dual Rear & 50 MP Front Camera                                           9
50 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                         9
50 MP + 5 MP + 2 MP Triple Rear & 12 MP Front Camera                                  8
200 MP + 8 MP Dual Rear & 50 MP Front Camera                                          8
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                 8
50 MP + 13 MP Dual Rear & 32 MP Front Camera                                          8
50 MP + 50 MP Dual Rear & 50 MP Front Camera                                          7
48 MP + 12 MP Dual Rear & 12 MP Front Camera                                          7
50 MP + 48 MP + 48 MP Triple Rear & 42 MP Front Camera                                7
48 MP Quad Rear & 16 MP Front Camera                                                  7
50 MP + 8 MP Dual Rear & 13 MP Front Camera                                           7
32 MP Rear & 8 MP Front Camera                                                        7
200 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                               7
32 MP Dual Rear & 8 MP Front Camera                                                   6
50 MP + 12 MP Dual Rear & 10 MP Front Camera                                          6
20 MP Rear & 8 MP Front Camera                                                        6
13 MP Rear Camera                                                                     6
50 MP + 8 MP + 5 MP Triple Rear & 12 MP Front Camera                                  6
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                                  6
50 MP Rear & 5 MP Front Camera                                                        6
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera                    5
50 MP Dual Rear & 13 MP Front Camera                                                  5
50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual Front Camera                             5
50 MP + Auxiliary lens Dual Rear & 8 MP Front Camera                                  5
50 MP + 12 MP + 5 MP Triple Rear & 12 MP Front Camera                                 5
13 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                         5
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                  5
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                  5
50 MP + 2 MP Dual Rear & 20 MP Front Camera                                           5
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                 5
64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                                  5
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                                 4
50 MP + 12 MP + 8 MP Triple Rear & 12 MP Front Camera                                 4
48 MP + 48 MP Dual Rear & 12 MP + Under-display FaceTime Camera Dual Front Camera     4
50 MP + 13 MP + Dedicated 3-in-1 light sensor Triple Rear & 32 MP Front Camera        4
50 MP + 12 MP + 8 MP Triple Rear & 10 MP Front Camera                                 4
64 MP Quad Rear & 32 MP Front Camera                                                  4
8 MP Rear Camera                                                                      4
48 MP Rear & 12 MP Front Camera                                                       4
50 MP + 2 MP Dual Rear & 13 MP Front Camera                                           4
200 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                               4
50 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                                 4
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                                 3
50 MP + 0.08 MP Dual Rear & 8 MP Front Camera                                         3
50 MP Quad Rear & 32 MP Front Camera                                                  3
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                                 3
50 MP Quad Rear & 8 MP Front Camera                                                   3
13 MP + 2 MP Dual Rear & 8 MP Front Camera                                            3
50 MP Dual Rear & 5 MP Front Camera                                                   3
8 MP Rear & 8 MP Front Camera                                                         3
200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera                  3
48 MP + 13 MP + 10.8 MP Triple Rear & 10.5 MP Front Camera                            3
50 MP + 50 MP + 10 MP Triple Rear & 50 MP Front Camera                                3
50 MP + 50 MP Dual Rear & 32 MP Front Camera                                          3
64 MP Dual Rear & 8 MP Front Camera                                                   3
200 MP + 8 MP Dual Rear & 32 MP Front Camera                                          3
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                                3
50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20 MP Dual Front Camera                   3
50 MP Dual Rear & 16 MP Front Camera                                                  3
48 MP + 5 MP Dual Rear & 16 MP Front Camera                                           3
48 MP Rear & 8 MP Front Camera                                                        3
13 MP Dual Rear & 8 MP Front Camera                                                   3
200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                                 3
12 MP + 12 MP Dual Rear & 10 MP Front Camera                                          3
48 MP Rear & 18 MP Front Camera                                                       3
200 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                                3
48 MP + 48 MP Dual Rear & 18 MP Front Camera                                          2
200 MP + 12 MP Dual Rear & 12 MP Front Camera                                         2
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                                  2
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                   2
48 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                                  2
32 MP Rear & 5 MP Front Camera                                                        2
64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                                  2
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                                 2
64 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                                   2
13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front Camera                                   2
200 MP + 8 MP Dual Rear & 20 MP Front Camera                                          2
108 MP + 8 MP Dual Rear & 20 MP Front Camera                                          2
64 MP + 13 MP Dual Rear & 13 MP Front Camera                                          2
48 MP + 13 MP Dual Rear & 13 MP Front Camera                                          2
48 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                                2
50 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                                 2
64 MP + 2 MP Dual Rear & 8 MP Front Camera                                            2
50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                                 2
64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                                  2
50 MP + 48 MP + 2 MP Triple Rear & 16 MP Front Camera                                 2
50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                                  2
48 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                                  2
48 MP Quad Rear & 13 MP Front Camera                                                  2
48 MP + 5 MP Dual Rear & 13 MP Front Camera                                           2
8 MP + 0.08 MP Dual Rear & 5 MP Front Camera                                          2
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                                    2
48 MP Quad Rear & 20 MP Front Camera                                                  2
64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32 MP Dual Front Camera                   2
64 MP + 13 MP Dual Rear & 32 MP Front Camera                                          2
50 MP + 50 MP + 8 MP Triple Rear & 20 MP Front Camera                                 2
48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP + 10 MP Dual Front Camera               2
200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 10 MP Dual Front Camera                  2
64 MP + 0.08 MP Dual Rear & 16 MP Front Camera                                        2
50 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                                2
200 MP + 12 MP + 2 MP Triple Rear & 50 MP Front Camera                                2
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                                  2
48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                   2
48 MP + 48 MP + 12 MP Triple Rear & 12 MP Front Camera                                1
12 MP + 12 MP Dual Rear & 12 MP Front Camera                                          1
108 MP + 2 MP Triple Rear & 8 MP Front Camera                                         1
50 MP + 8 MP Dual Rear & 8 MP Front Camera                                            1
108 MP + Macro Dual Rear & 13 MP Front Camera                                         1
48 MP + Depth Sensor Dual Rear & 8 MP Front Camera                                    1
50 MP + 13 MP + 10 MP Triple Rear & 32 MP Front Camera                                1
200 MP + 200 MP + 50 MP Triple Rear & 50 MP Front Camera                              1
200 MP Penta Rear & 50 MP Front Camera                                                1
64 MP + 50 MP + 50 MP Triple Rear & 50 MP Front Camera                                1
50 MP + 48 MP + 32 MP Triple Rear & 16 MP Front Camera                                1
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                                         1
64 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera                                1
13 MP + 2 MP Dual Rear & 5 MP Front Camera                                            1
50 MP + 13 MP + 10 MP Triple Rear & 50 MP Front Camera                                1
64 MP + 5 MP Dual Rear & 13 MP Front Camera                                           1
48 MP + 8 MP Dual Rear & 13 MP Front Camera                                           1
50 MP + 48 MP Dual Rear & 10.5 MP Front Camera                                        1
50 MP + 48 MP + 48 MP Triple Rear & 10.5 MP Front Camera                              1
50 MP + 8 MP + 2 MP Triple Rear & 12 MP Front Camera                                  1
50 MP + 8 MP + 5 MP Triple Rear & 13 MP Front Camera                                  1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                                        1
50 MP + 12 MP Dual Rear & 10.5 MP Front Camera                                        1
108 MP + 8 MP Dual Rear & 13 MP Front Camera                                          1
64 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                                  1
5 MP Rear Camera                                                                      1
50 MP + 5 MP Dual Rear & 8 MP Front Camera                                            1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20 MP Dual Front Camera                   1
64 MP + 8 MP + 2 MP Triple Rear & 44 MP + 8 MP Dual Front Camera                      1
64 MP Quad Rear & 32 MP + 8 MP Dual Front Camera                                      1
64 MP Quad Rear & 20 MP Front Camera                                                  1
48 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                                  1
13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                   1
64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20 MP Dual Front Camera                   1
64 MP + 2 MP Dual Rear & 16 MP Front Camera                                           1
50 MP + 50 MP + 16 MP Triple Rear & 16 MP Front Camera                                1
64 MP + 50 MP + 8 MP Triple Rear & 32 MP Front Camera                                 1
64 MP + 32 MP + 8 MP Triple Rear & 32 MP Front Camera                                 1
64 MP + 50 MP + 50 MP Triple Rear & 16 MP Front Camera                                1
50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front Camera                                 1
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                                        1
108 MP Quad Rear & 32 MP Front Camera                                                 1
50 MP + 50 MP + 12 MP Triple Rear & 32 MP + 32 MP Dual Front Camera                   1
108 MP + 2 MP Dual Rear & 16 MP Front Camera                                          1
13 MP + 5 MP + 5 MP Triple Rear & 16 MP Front Camera                                  1
Foldable Display, Dual Display                                                        1
13 MP Rear & Main Front Camera                                                        1
20 MP Rear Camera                                                                     1
12 MP + 12 MP Dual Rear & 7 MP Front Camera                                           1
64 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                                1
12 MP + 5 MP Dual Rear & 16 MP Front Camera                                           1
50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                                   1
16 MP Dual Rear & 8 MP Front Camera                                                   1
48 MP + 13 MP + 13 MP Triple Rear & 16 MP Front Camera                                1
64 MP + 13 MP + 5 MP Triple Rear & 24 MP Front Camera                                 1
12 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                                   1
64 MP Quad Rear & 16 MP Front Camera                                                  1
48 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                                   1
13 MP Quad Rear & 8 MP Front Camera                                                   1
12 MP Quad Rear & 13 MP Front Camera                                                  1
16 MP + 5 MP Dual Rear & 25 MP Front Camera                                           1
Name: count, dtype: int64