<a href="https://colab.research.google.com/github/adilkamal2478/Adil_Pandas_Data_Preprocessing/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np

In [70]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [71]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [72]:
df = pd.read_excel("/content/drive/MyDrive/Data_processing/smartprix-phones-table.xlsx", engine="openpyxl")

In [73]:
df

                                                  model      price  rating  \
0                                   Apple iPhone 18 Pro  ₹1,64,900    85.0
1                      Vivo T4 Pro 5G (8GB RAM + 256GB)    ₹29,999    72.0
2                                      Apple iPhone Duo  ₹2,99,900    84.0
3                               Apple iPhone 18 Pro Max  ₹1,79,900    86.0
4                         Realme P1 5G (8GB RAM+ 128GB)    ₹14,999    58.0
5                               Motorola Edge 70 Fusion    ₹27,695    70.0
6                                       Apple iPhone 17    ₹82,900    76.0
7                                            Vivo T5 5G    ₹34,999    71.0
8                                    Xiaomi Redmi 17 5G    ₹23,999    61.0
9                                        Poco X7 Pro 5G    ₹23,999    70.0
10              Samsung Galaxy F16 5G (6GB RAM + 128GB)    ₹13,999    55.0
11                                     Poco X8 Power 5G    ₹35,999    76.0
12                                    OnePlus Nord 5 5G    ₹33,999    75.0
13               Motorola Moto G34 5G (8GB RAM + 128GB)    ₹14,999    55.0
14                                           Vivo T4 5G    ₹24,999    66.0
15                                         Realme P3 5G    ₹15,999    61.0
16                                      Apple iPhone 16    ₹69,900    70.0
17                             Samsung Galaxy S25 Ultra    ₹99,999    92.0
18                      Vivo T4 Ultra (12GB RAM+ 256GB)    ₹37,999    75.0
19                                   Xiaomi Redmi 13 5G    ₹12,499    58.0
20                           Oppo K13 (8GB RAM + 256GB)    ₹23,999    63.0
21                              Motorola Edge 60 Fusion    ₹24,999    67.0
22                                 Motorola Edge 70 Pro    ₹39,849    83.0
23                                Samsung Galaxy A17 5G    ₹19,499    58.0
24                               Apple iPhone Duo (2TB)  ₹4,49,900    86.0
25                                 Xiaomi Redmi Note 14    ₹16,499    63.0
26                                      OPPO Reno 14 5G    ₹44,999    76.0
27                     Oppo K13 Turbo (8GB RAM + 256GB)    ₹27,999    70.0
28                                     Realme P4 Pro 5G    ₹28,999    71.0
29                          Samsung Galaxy S26 Ultra 5G  ₹1,30,999    94.0
30                                Samsung Galaxy S25 FE    ₹53,990    75.0
31                              Apple iPhone 17 Pro Max  ₹1,43,990    81.0
32                                 Motorola Edge 60 Pro    ₹30,190    76.0
33                              Motorola Edge 60 Stylus    ₹20,560    67.0
34                                       OnePlus Nord 6    ₹46,999    85.0
35                                        Realme P4s 5G    ₹34,999    71.0
36                                          Vivo T5x 5G    ₹27,228    66.0
37                                    Tecno Spark Go 5G     ₹9,999    52.0
38                                          Vivo V70 5G    ₹59,999    81.0
39                   Nothing Phone 2a (8GB RAM + 256GB)    ₹24,999    70.0
40                      Realme GT 7T (12GB RAM + 256GB)    ₹34,499    77.0
41                               Apple iPhone Duo (1TB)  ₹3,74,900    85.0
42                                           Poco X7 5G    ₹17,999    64.0
43                                  Motorola Edge 70 5G    ₹32,490    75.0
44                                          Vivo V70 FE    ₹38,000    77.0
45                                      Apple iPhone 15    ₹59,900    66.0
46                                   Samsung Galaxy F05     ₹6,499     NaN
47                                           Vivo S2 5G    ₹39,999    67.0
48                          Apple iPhone 18 Pro (512GB)  ₹1,89,900    85.0
49                                Samsung Galaxy S25 5G    ₹66,000    77.0
50                                  Apple iPhone 17 Pro  ₹1,30,490    74.0
51                       Realme P3 5G (8GB RAM + 128GB)    ₹16,999    63.0
52                        OPPO K13x 5G (6GB RAM +128GB)    ₹16,999    54.0
53                                          Vivo T4R 5G    ₹22,999    66.0
54                   Realme P3 Pro 5G (12GB RAM +256GB)    ₹23,999    66.0
55                                 Motorola Moto G35 5G    ₹12,499    57.0
56                                           Poco X8 5G    ₹29,999    67.0
57                             Samsung Galaxy S24 FE 5G    ₹39,999    70.0
58                                Samsung Galaxy M47 5G    ₹26,915    67.0
59                                         Realme P1 5G    ₹13,999    58.0
60                                   Motorola Signature    ₹59,899    92.0
61                                Samsung Galaxy A36 5G    ₹28,000    64.0
62           Motorola Edge 50 Fusion (12GB RAM + 256GB)    ₹22,790    68.0
63                        Apple iPhone 18 Pro Max (1TB)  ₹2,54,900    88.0
64                    Poco M7 Plus 5G (4GB RAM + 128GB)    ₹15,499    58.0
65                         Poco X7 5G (8GB RAM + 256GB)    ₹19,999    66.0
66                                        Realme P3x 5G    ₹12,999    55.0
67                                        Realme P4x 5G    ₹21,939    62.0
68                Xiaomi Redmi 14C 5G (6GB RAM + 128GB)    ₹11,999    54.0
69                          Realme 12X (6GB RAM +128GB)    ₹12,499    55.0
70                                         Vivo X300 FE    ₹84,999    92.0
71                    Vivo T4 Pro 5G (12GB RAM + 256GB)    ₹31,999    74.0
72                        Apple iPhone 18 Pro Max (2TB)  ₹3,29,900    89.0
73                                          iQOO Z11 5G    ₹34,999    71.0
74                                      Google Pixel 11    ₹82,300    74.0
75                      Apple iPhone 18 Pro Max (512GB)  ₹2,04,900    88.0
76                                      Oppo F31 Pro 5G    ₹25,999    66.0
77                       Poco X7 Pro (12GB RAM + 256GB)    ₹25,999    71.0
78                      Vivo X200 FE (16GB RAM + 512GB)    ₹59,999    86.0
79                Infinix Note 40X 5G (12GB RAM +256GB)    ₹15,999    62.0
80                                 Nothing Phone 3a Pro    ₹27,999    66.0
81                                           OnePlus 15    ₹85,999    94.0
82                  Realme 15 Pro 5G (12GB RAM + 256GB)    ₹33,499    76.0
83                                      Apple iPhone 13    ₹45,690    55.0
84                      Poco X8 Power (8GB RAM + 256GB)    ₹38,999    79.0
85                                        iQOO Z11xA 5G    ₹28,999    64.0
86                                  Infinix Note 50X 5G    ₹13,499    55.0
87                                Samsung Galaxy S26 5G    ₹79,999    80.0
88                                Samsung Galaxy A56 5G    ₹34,999    63.0
89                                  OPPO Reno 14 Pro 5G    ₹49,890    85.0
90          Motorola Moto G37 Power 5G (4GB RAM + 64GB)    ₹15,474    55.0
91                            Samsung Galaxy F70 Pro 5G    ₹26,349    66.0
92                   Samsung Galaxy S24 5G (Snapdragon)    ₹49,999    72.0
93                                   Realme P4 Power 5G    ₹30,379    72.0
94                                      OPPO Reno 16 5G    ₹66,999    79.0
95                                           Poco M7 5G    ₹12,499    53.0
96                              Xiaomi Redmi Note 17 5G    ₹27,999    61.0
97                                 OnePlus Nord CE 6 5G    ₹37,999    74.0
98        Motorola Edge 70 Fusion 5G (8GB RAM + 256 GB)    ₹35,884    71.0
99                 Realme 14 Pro Plus (8GB RAM + 256GB)    ₹25,999    67.0
100                      Boltt Ace 5G (8GB RAM + 128GB)    ₹14,999    55.0
101                          Samsung Galaxy Z Fold 8 5G  ₹1,74,999    92.0
102                               Samsung Galaxy F16 5G    ₹12,499    54.0
103                                         Vivo T5 Pro    ₹37,420    72.0
104                                     Oppo Find X9 5G    ₹84,999    89.0
105                                             iQOO 15    ₹76,999    94.0
106                           Apple iPhone 18 Pro (1TB)  ₹2,39,900    86.0
107                         Xiaomi Redmi Note 15 Pro 5G    ₹31,999    72.0
108                Xiaomi Redmi 17 5G (8GB RAM + 128GB)    ₹26,999    62.0
109                                          Poco F7 5G    ₹35,999    76.0
110                                            OPPO K13    ₹21,999    62.0
111                                          OnePlus N6    ₹24,999    59.0
112                               Samsung Galaxy A07 5G    ₹16,900    57.0
113                                        Boltt Ace 5G    ₹12,999    53.0
114                         Xiaomi Redmi Note 14 Pro 5G    ₹21,999    62.0
115                     Realme P3x 5G (8GB RAM + 128GB)    ₹13,999    57.0
116      Motorola Edge 70 Fusion 5G (12GB RAM + 256 GB)    ₹34,980    72.0
117                                  Google Pixel 10 5G    ₹67,340    75.0
118             Samsung Galaxy F16 5G (8GB RAM + 128GB)    ₹15,499    55.0
119           Motorola Moto G37 Power (8GB RAM + 128GB)    ₹19,900    58.0
120                  Nothing Phone 3 (16GB RAM + 512GB)    ₹51,999    84.0
121                                    Nothing Phone 4a    ₹35,799    71.0
122                 OnePlus Nord 4 5G (8GB RAM + 256GB)    ₹29,999    70.0
123                          Motorola Moto G67 Power 5G    ₹22,949    62.0
124                    Vivo V70 FE 5G (8GB RAM + 256GB)    ₹44,999    79.0
125                                            iQOO 15R    ₹53,999    84.0
126                  Realme P1 Pro 5G (8GB RAM + 256GB)    ₹16,999    59.0
127                                    Google Pixel 10A    ₹52,190    76.0
128                                      Moto G57 Power    ₹20,999    57.0
129                                       Realme P4R 5G    ₹19,890    57.0
130                                  Oppo K13 Turbo Pro    ₹29,999    71.0
131                                     Realme GT 8 Pro    ₹72,999    94.0
132                                     Vivo X300 Ultra  ₹1,59,999    98.0
133                                            OPPO K14    ₹22,998    62.0
134                       Samsung Galaxy Z Fold 8 Ultra  ₹1,94,999    98.0
135                                      Poco X8 Pro 5G    ₹39,690    76.0
136                             Apple iPhone 16 Pro Max  ₹1,34,900    80.0
137                                 Motorola Edge 50 5G    ₹22,990    70.0
138                                         OPPO A6x 5G    ₹18,999    50.0
139                             Samsung Galaxy S25 Edge    ₹60,800    80.0
140                                       Realme C63 5G    ₹10,999    53.0
141             Samsung Galaxy A06 5G (6GB RAM + 128GB)    ₹14,499    53.0
142                                      OnePlus 13s 5G    ₹54,999    80.0
143                                    Nokia 300 Charge     ₹2,599     NaN
144                   Realme P3 Pro 5G (8GB RAM +256GB)    ₹21,999    64.0
145                            Apple iPhone Duo (512GB)  ₹3,24,900    85.0
146                              Nothing Phone (4a) Pro    ₹45,990    75.0
147                                OnePlus Nord CE 5 5G    ₹33,999    71.0
148                       iQOO Neo 10 (8GB RAM + 256GB)    ₹43,999    80.0
149                        Motorola Edge 70 Pro Plus 5G    ₹48,780    84.0
150             Samsung Galaxy A16 5G (6GB RAM + 128GB)    ₹15,999    57.0
151                        Vivo T5 5G (8GB RAM + 256GB)    ₹44,999    74.0
152                            Samsung Galaxy S24 Ultra    ₹99,990    86.0
153                                         Vivo Y11 5G    ₹17,999     NaN
154                   Realme P3 Ultra (8GB RAM + 256GB)    ₹28,999    67.0
155                        Realme 14x (8GB RAM + 128GB)    ₹15,999    57.0
156               Infinix Hot 50 5G (8 GB RAM + 128 GB)    ₹10,999    53.0
157                        Realme Narzo 90x (8GB+128GB)    ₹23,499    59.0
158                                        OPPO K14x 5G    ₹18,499    54.0
159                                      OnePlus 15R 5G    ₹59,999    83.0
160                       Xiaomi Redmi Note 15 Pro Plus    ₹39,999    79.0
161                                         Poco M8x 5G    ₹19,994    61.0
162                                  Xiaomi Redmi 15 5G    ₹21,499    61.0
163                                Apple iPhone 15 Plus    ₹69,900    67.0
164                                          OnePlus 13    ₹63,157    86.0
165                                 Google Pixel 11 Pro  ₹1,19,999    85.0
166                               Samsung Galaxy M17 5G    ₹17,930    54.0
167                 OnePlus Nord 6 5G (12GB RAM +256GB)    ₹52,999    86.0
168                               Samsung Galaxy A57 5G    ₹56,999    74.0
169                       Vivo T4 5G (12GB RAM + 256GB)    ₹28,999    68.0
170                                Xiaomi Redmi Turbo 5    ₹41,999    76.0
171                   Poco M7 Plus 5G (8GB RAM + 128GB)    ₹17,999    59.0
172                                    Realme P2 Pro 5G    ₹17,999    63.0
173          Motorola Edge 70 Pro 5G (12GB RAM + 256GB)    ₹42,865    84.0
174                              Xiaomi Redmi A7 Pro 5G    ₹14,999    54.0
175                                 OPPO Reno 15 Pro 5G    ₹60,999    86.0
176                               Infinix Hot 70 Pro 5G    ₹24,999    62.0
177             Motorola Edge 60 Pro (12GB RAM + 256GB)    ₹35,385    77.0
178                                       Realme 14x 5G    ₹14,999    55.0
179                                           Boltt Evo     ₹9,999     NaN
180                       Vivo T4R 5G (8GB RAM + 256GB)    ₹24,999    66.0
181                                     Google Pixel 8A    ₹36,999    66.0
182                        Vivo T5 5G (8GB RAM + 128GB)    ₹39,999    72.0
183                                     OPPO Reno 15 5G    ₹47,999    79.0
184                                       OPPO Reno 16C    ₹49,999    75.0
185                     Realme GT 7T (12GB RAM + 512GB)    ₹37,499    79.0
186                           Apple iPhone 18 Pro (2TB)  ₹3,14,900    88.0
187                             Xiaomi Redmi Note 15 5G    ₹28,999    70.0
188                             Apple iPhone 15 (256GB)    ₹69,900    66.0
189                                         Vivo Y21 5G    ₹22,499    58.0
190                               Nothing Phone 3a Lite    ₹27,999    63.0
191                                  Tecno Pova Slim 5G    ₹20,999    58.0
192                     Oppo K13 Turbo Pro (12GB+256GB)    ₹42,490    72.0
193                             Apple iPhone 16 (256GB)    ₹79,900    70.0
194                      Realme GT 7 (12GB RAM + 512GB)    ₹48,999    85.0
195                               Samsung Galaxy F36 5G    ₹22,450    62.0
196                               Samsung Galaxy M56 5G    ₹31,999    58.0
197                                    Realme P3 Pro 5G    ₹20,999    63.0
198                                     OPPO F33 Pro 5G    ₹39,999    67.0
199                                     Poco X8 Pro Max    ₹48,999    83.0
200                  Realme P4 Pro 5G (8GB RAM + 256GB)    ₹30,999    72.0
201                                  Google Pixel 8 Pro    ₹49,999    74.0
202                              OnePlus Nord CE 6 Lite    ₹28,065    63.0
203                    OnePlus 15 5G (16GB RAM + 512GB)    ₹93,999    95.0
204                             Apple iPhone 17 (512GB)  ₹1,02,900    77.0
205                                        Realme GT 7T    ₹32,999    76.0
206                  Realme GT 8 Pro (16GB RAM + 512GB)    ₹78,999    95.0
207                                         Vivo V40 5G    ₹34,999    70.0
208                                          Realme 12X    ₹11,999    54.0
209                               Samsung Galaxy M36 5G    ₹21,999    58.0
210       Motorola Edge 60 Fusion 5G (12GB RAM + 256GB)    ₹29,499    68.0
211                              Infinix Note 60 Pro 5G    ₹33,949    74.0
212                       Vivo T5x 5G (8GB RAM + 128GB)    ₹29,203    67.0
213                                    Apple iPhone 17e    ₹64,900    63.0
214                     OnePlus N6 5G (6GB RAM + 128GB)    ₹26,999    61.0
215                               Samsung Galaxy A27 5G    ₹32,950    63.0
216                         iQOO 15R (12GB RAM + 256GB)    ₹59,999    85.0
217                 Motorola Signature (16GB RAM + 1TB)    ₹69,999    94.0
218             Samsung Galaxy A17 5G (8GB RAM + 128GB)    ₹23,499    59.0
219                        Poco M7 5G (8GB RAM + 128GB)    ₹13,499    53.0
220                         Boltt Evo (6GB RAM + 128GB)    ₹10,999    50.0
221                                Realme Narzo 100x 5G    ₹19,859    58.0
222             Samsung Galaxy S25 FE (8GB RAM + 256GB)    ₹65,999    76.0
223                               Samsung Galaxy A37 5G    ₹38,999    66.0
224         Samsung Galaxy S26 Ultra (12GB RAM + 512GB)  ₹1,50,999    94.0
225                      Boltt Ace 5G (6GB RAM + 128GB)    ₹13,999    54.0
226                  Oppo F31 Pro 5G (12GB RAM + 256GB)    ₹29,999    68.0
227                               Samsung Galaxy F17 5G    ₹17,999    57.0
228            Samsung Galaxy F70e 5G (6GB RAM + 128GB)    ₹18,650    55.0
229                                   Google Pixel 8 5G    ₹37,999    66.0
230               Realme GT 2 Pro 5G (12GB RAM + 256GB)    ₹27,900    70.0
231                                     Vivo T5 Lite 5G    ₹20,499    55.0
232                      Vivo V70 5G (12GB RAM + 256GB)    ₹64,999    84.0
233                                    Realme 16 Pro 5G    ₹37,999    77.0
234                                       Poco M8 Power    ₹24,390    63.0
235                                 Xiaomi Redmi 15C 5G    ₹17,499    55.0
236                                    Vivo X300 Pro 5G  ₹1,19,999    94.0
237                                   Infinix GT 30 Pro    ₹31,999    75.0
238                       Samsung Galaxy S24 FE (256GB)    ₹45,999    71.0
239                               Samsung Galaxy A35 5G    ₹29,990    63.0
240                           Poco X8 (8GB RAM + 256GB)    ₹35,999    70.0
241                                        Xiaomi 17 5G    ₹89,999    94.0
242                               Samsung Galaxy F15 5G    ₹13,499    53.0
243                          Motorola Moto G37 Power 5G    ₹17,132    55.0
244                        Vivo S2 5G (8GB RAM + 256GB)    ₹44,999    68.0
245                                           iQOO Z11x    ₹27,999    64.0
246             Samsung Galaxy A17 5G (8GB RAM + 256GB)    ₹27,999    61.0
247                                         OnePlus N6x    ₹20,999     NaN
248                                           Vivo V60e    ₹34,999    75.0
249                                    Apple iPhone Air  ₹1,01,900    64.0
250             Motorola Edge 60 Pro (16GB RAM + 512GB)    ₹40,999    80.0
251             Samsung Galaxy A56 5G (8GB RAM + 256GB)    ₹38,968    64.0
252                                Lava Virat V1 Pro 5G    ₹15,999    52.0
253                       Vivo T5x 5G (8GB RAM + 256GB)    ₹32,889    67.0
254           Samsung Galaxy S26 Ultra (16GB RAM + 1TB)  ₹1,80,999    97.0
255                                       Oppo Reno 15c    ₹41,999    68.0
256                                         Oppo F31 5G    ₹26,999    64.0
257                                        Vivo Y400 5G    ₹31,991    64.0
258                                     Vivo T4 Lite 5G    ₹18,899    52.0
259                                  Nothing Phone 3 5G    ₹79,999    80.0
260                                     Google Pixel 9A    ₹49,699    68.0
261              OnePlus Nord CE 6 5G (8GB RAM + 256GB)    ₹41,999    75.0
262                                  Tecno Pova Curve 2    ₹26,499    63.0
263              Xiaomi Redmi Note 14 (8GB RAM + 256GB)    ₹24,999    66.0
264                             Samsung Galaxy Z Flip 3    ₹41,499    67.0

## Data Assessing

### Quality Issues

1. **model** - some brands are written diiferently like OPPO in model column `consistency`
2. **price** - has unneccesary '₹' `validity`
3. **price** - has ',' between numbers `validity`
4. **price** -  
5. **ratings** - missing values `completeness`
6. **processor** - 619 , 880
7.
8. **memory** - incorrect values in rows (284,501,880) `validity`
9. **battery** - incorrect values in rows(880) `validity`
10. **display** - sometimes frequency is not available `completeness`
11. **display** - incorrect values in rows(880) `validity`
12. certain phones are foldable and the info is scattered `validity`
13. **camera** - words like Dual, Triple and Quad are used to represent number of cameras and front and rear cameras are separated by '&'
14. **camera** - problem with rows (4,26,43,103,136,145,147,266,274,306,311,327,405,435,452,467,468,484,520,539,551,560,606,619,630,654,663,673,674,675,678,691,726,743,744,755,756,766,771,796,802,812,825,880,936,1007
)- 714,900,902,1015 missings `validity`
15. **card** - sometimes contains info about os and camera `validity`
16. **os** - sometimes contains info about bluetooth and fm radio `validity`
17. **os** - issue with rows (324,378) `validity`
18. **os** - sometimes contains os version name like lollipop `consistency`
19. missing values in camera, card and os `completeness`
20. datatype  of price and rating is incorrect `validity`



### Tidiness Issues

1. **sim** - can be split into 3 cols has_5g, has_NFC, has_IR_Blaster
2. **ram** - can be split into 2 cols RAM and ROM
3. **processor** - can be split into processor name, cores and cpu speed.
4. **battery** - can be split into battery capacity, fast_charging_available
5. **display** - can be split into size, resolution_width, resolution_height and frequency
6. **camera** - can be split into front and rear camera
7. **card** - can be split into supported, extended_upto

In [74]:
df1 = df.copy()

In [75]:
df1['price'] = df1['price'].str.replace('₹','').str.replace(',','').astype('int')

In [76]:
df1 = df1.reset_index()

In [77]:
df1['index'] = df1['index'] + 2

In [78]:
df1.head()

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
3,5,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [79]:
df1 = df1[df1['price'] > 4999]

In [80]:
df1

      index                                              model   price  \
0         2                                Apple iPhone 18 Pro  164900
1         3                   Vivo T4 Pro 5G (8GB RAM + 256GB)   29999
2         4                                   Apple iPhone Duo  299900
3         5                            Apple iPhone 18 Pro Max  179900
4         6                      Realme P1 5G (8GB RAM+ 128GB)   14999
5         7                            Motorola Edge 70 Fusion   27695
6         8                                    Apple iPhone 17   82900
7         9                                         Vivo T5 5G   34999
8        10                                 Xiaomi Redmi 17 5G   23999
9        11                                     Poco X7 Pro 5G   23999
10       12            Samsung Galaxy F16 5G (6GB RAM + 128GB)   13999
11       13                                   Poco X8 Power 5G   35999
12       14                                  OnePlus Nord 5 5G   33999
13       15             Motorola Moto G34 5G (8GB RAM + 128GB)   14999
14       16                                         Vivo T4 5G   24999
15       17                                       Realme P3 5G   15999
16       18                                    Apple iPhone 16   69900
17       19                           Samsung Galaxy S25 Ultra   99999
18       20                    Vivo T4 Ultra (12GB RAM+ 256GB)   37999
19       21                                 Xiaomi Redmi 13 5G   12499
20       22                         Oppo K13 (8GB RAM + 256GB)   23999
21       23                            Motorola Edge 60 Fusion   24999
22       24                               Motorola Edge 70 Pro   39849
23       25                              Samsung Galaxy A17 5G   19499
24       26                             Apple iPhone Duo (2TB)  449900
25       27                               Xiaomi Redmi Note 14   16499
26       28                                    OPPO Reno 14 5G   44999
27       29                   Oppo K13 Turbo (8GB RAM + 256GB)   27999
28       30                                   Realme P4 Pro 5G   28999
29       31                        Samsung Galaxy S26 Ultra 5G  130999
30       32                              Samsung Galaxy S25 FE   53990
31       33                            Apple iPhone 17 Pro Max  143990
32       34                               Motorola Edge 60 Pro   30190
33       35                            Motorola Edge 60 Stylus   20560
34       36                                     OnePlus Nord 6   46999
35       37                                      Realme P4s 5G   34999
36       38                                        Vivo T5x 5G   27228
37       39                                  Tecno Spark Go 5G    9999
38       40                                        Vivo V70 5G   59999
39       41                 Nothing Phone 2a (8GB RAM + 256GB)   24999
40       42                    Realme GT 7T (12GB RAM + 256GB)   34499
41       43                             Apple iPhone Duo (1TB)  374900
42       44                                         Poco X7 5G   17999
43       45                                Motorola Edge 70 5G   32490
44       46                                        Vivo V70 FE   38000
45       47                                    Apple iPhone 15   59900
46       48                                 Samsung Galaxy F05    6499
47       49                                         Vivo S2 5G   39999
48       50                        Apple iPhone 18 Pro (512GB)  189900
49       51                              Samsung Galaxy S25 5G   66000
50       52                                Apple iPhone 17 Pro  130490
51       53                     Realme P3 5G (8GB RAM + 128GB)   16999
52       54                      OPPO K13x 5G (6GB RAM +128GB)   16999
53       55                                        Vivo T4R 5G   22999
54       56                 Realme P3 Pro 5G (12GB RAM +256GB)   23999
55       57                               Motorola Moto G35 5G   12499
56       58                                         Poco X8 5G   29999
57       59                           Samsung Galaxy S24 FE 5G   39999
58       60                              Samsung Galaxy M47 5G   26915
59       61                                       Realme P1 5G   13999
60       62                                 Motorola Signature   59899
61       63                              Samsung Galaxy A36 5G   28000
62       64         Motorola Edge 50 Fusion (12GB RAM + 256GB)   22790
63       65                      Apple iPhone 18 Pro Max (1TB)  254900
64       66                  Poco M7 Plus 5G (4GB RAM + 128GB)   15499
65       67                       Poco X7 5G (8GB RAM + 256GB)   19999
66       68                                      Realme P3x 5G   12999
67       69                                      Realme P4x 5G   21939
68       70              Xiaomi Redmi 14C 5G (6GB RAM + 128GB)   11999
69       71                        Realme 12X (6GB RAM +128GB)   12499
70       72                                       Vivo X300 FE   84999
71       73                  Vivo T4 Pro 5G (12GB RAM + 256GB)   31999
72       74                      Apple iPhone 18 Pro Max (2TB)  329900
73       75                                        iQOO Z11 5G   34999
74       76                                    Google Pixel 11   82300
75       77                    Apple iPhone 18 Pro Max (512GB)  204900
76       78                                    Oppo F31 Pro 5G   25999
77       79                     Poco X7 Pro (12GB RAM + 256GB)   25999
78       80                    Vivo X200 FE (16GB RAM + 512GB)   59999
79       81              Infinix Note 40X 5G (12GB RAM +256GB)   15999
80       82                               Nothing Phone 3a Pro   27999
81       83                                         OnePlus 15   85999
82       84                Realme 15 Pro 5G (12GB RAM + 256GB)   33499
83       85                                    Apple iPhone 13   45690
84       86                    Poco X8 Power (8GB RAM + 256GB)   38999
85       87                                      iQOO Z11xA 5G   28999
86       88                                Infinix Note 50X 5G   13499
87       89                              Samsung Galaxy S26 5G   79999
88       90                              Samsung Galaxy A56 5G   34999
89       91                                OPPO Reno 14 Pro 5G   49890
90       92        Motorola Moto G37 Power 5G (4GB RAM + 64GB)   15474
91       93                          Samsung Galaxy F70 Pro 5G   26349
92       94                 Samsung Galaxy S24 5G (Snapdragon)   49999
93       95                                 Realme P4 Power 5G   30379
94       96                                    OPPO Reno 16 5G   66999
95       97                                         Poco M7 5G   12499
96       98                            Xiaomi Redmi Note 17 5G   27999
97       99                               OnePlus Nord CE 6 5G   37999
98      100      Motorola Edge 70 Fusion 5G (8GB RAM + 256 GB)   35884
99      101               Realme 14 Pro Plus (8GB RAM + 256GB)   25999
100     102                     Boltt Ace 5G (8GB RAM + 128GB)   14999
101     103                         Samsung Galaxy Z Fold 8 5G  174999
102     104                              Samsung Galaxy F16 5G   12499
103     105                                        Vivo T5 Pro   37420
104     106                                    Oppo Find X9 5G   84999
105     107                                            iQOO 15   76999
106     108                          Apple iPhone 18 Pro (1TB)  239900
107     109                        Xiaomi Redmi Note 15 Pro 5G   31999
108     110               Xiaomi Redmi 17 5G (8GB RAM + 128GB)   26999
109     111                                         Poco F7 5G   35999
110     112                                           OPPO K13   21999
111     113                                         OnePlus N6   24999
112     114                              Samsung Galaxy A07 5G   16900
113     115                                       Boltt Ace 5G   12999
114     116                        Xiaomi Redmi Note 14 Pro 5G   21999
115     117                    Realme P3x 5G (8GB RAM + 128GB)   13999
116     118     Motorola Edge 70 Fusion 5G (12GB RAM + 256 GB)   34980
117     119                                 Google Pixel 10 5G   67340
118     120            Samsung Galaxy F16 5G (8GB RAM + 128GB)   15499
119     121          Motorola Moto G37 Power (8GB RAM + 128GB)   19900
120     122                 Nothing Phone 3 (16GB RAM + 512GB)   51999
121     123                                   Nothing Phone 4a   35799
122     124                OnePlus Nord 4 5G (8GB RAM + 256GB)   29999
123     125                         Motorola Moto G67 Power 5G   22949
124     126                   Vivo V70 FE 5G (8GB RAM + 256GB)   44999
125     127                                           iQOO 15R   53999
126     128                 Realme P1 Pro 5G (8GB RAM + 256GB)   16999
127     129                                   Google Pixel 10A   52190
128     130                                     Moto G57 Power   20999
129     131                                      Realme P4R 5G   19890
130     132                                 Oppo K13 Turbo Pro   29999
131     133                                    Realme GT 8 Pro   72999
132     134                                    Vivo X300 Ultra  159999
133     135                                           OPPO K14   22998
134     136                      Samsung Galaxy Z Fold 8 Ultra  194999
135     137                                     Poco X8 Pro 5G   39690
136     138                            Apple iPhone 16 Pro Max  134900
137     139                                Motorola Edge 50 5G   22990
138     140                                        OPPO A6x 5G   18999
139     141                            Samsung Galaxy S25 Edge   60800
140     142                                      Realme C63 5G   10999
141     143            Samsung Galaxy A06 5G (6GB RAM + 128GB)   14499
142     144                                     OnePlus 13s 5G   54999
144     146                  Realme P3 Pro 5G (8GB RAM +256GB)   21999
145     147                           Apple iPhone Duo (512GB)  324900
146     148                             Nothing Phone (4a) Pro   45990
147     149                               OnePlus Nord CE 5 5G   33999
148     150                      iQOO Neo 10 (8GB RAM + 256GB)   43999
149     151                       Motorola Edge 70 Pro Plus 5G   48780
150     152            Samsung Galaxy A16 5G (6GB RAM + 128GB)   15999
151     153                       Vivo T5 5G (8GB RAM + 256GB)   44999
152     154                           Samsung Galaxy S24 Ultra   99990
153     155                                        Vivo Y11 5G   17999
154     156                  Realme P3 Ultra (8GB RAM + 256GB)   28999
155     157                       Realme 14x (8GB RAM + 128GB)   15999
156     158              Infinix Hot 50 5G (8 GB RAM + 128 GB)   10999
157     159                       Realme Narzo 90x (8GB+128GB)   23499
158     160                                       OPPO K14x 5G   18499
159     161                                     OnePlus 15R 5G   59999
160     162                      Xiaomi Redmi Note 15 Pro Plus   39999
161     163                                        Poco M8x 5G   19994
162     164                                 Xiaomi Redmi 15 5G   21499
163     165                               Apple iPhone 15 Plus   69900
164     166                                         OnePlus 13   63157
165     167                                Google Pixel 11 Pro  119999
166     168                              Samsung Galaxy M17 5G   17930
167     169                OnePlus Nord 6 5G (12GB RAM +256GB)   52999
168     170                              Samsung Galaxy A57 5G   56999
169     171                      Vivo T4 5G (12GB RAM + 256GB)   28999
170     172                               Xiaomi Redmi Turbo 5   41999
171     173                  Poco M7 Plus 5G (8GB RAM + 128GB)   17999
172     174                                   Realme P2 Pro 5G   17999
173     175         Motorola Edge 70 Pro 5G (12GB RAM + 256GB)   42865
174     176                             Xiaomi Redmi A7 Pro 5G   14999
175     177                                OPPO Reno 15 Pro 5G   60999
176     178                              Infinix Hot 70 Pro 5G   24999
177     179            Motorola Edge 60 Pro (12GB RAM + 256GB)   35385
178     180                                      Realme 14x 5G   14999
179     181                                          Boltt Evo    9999
180     182                      Vivo T4R 5G (8GB RAM + 256GB)   24999
181     183                                    Google Pixel 8A   36999
182     184                       Vivo T5 5G (8GB RAM + 128GB)   39999
183     185                                    OPPO Reno 15 5G   47999
184     186                                      OPPO Reno 16C   49999
185     187                    Realme GT 7T (12GB RAM + 512GB)   37499
186     188                          Apple iPhone 18 Pro (2TB)  314900
187     189                            Xiaomi Redmi Note 15 5G   28999
188     190                            Apple iPhone 15 (256GB)   69900
189     191                                        Vivo Y21 5G   22499
190     192                              Nothing Phone 3a Lite   27999
191     193                                 Tecno Pova Slim 5G   20999
192     194                    Oppo K13 Turbo Pro (12GB+256GB)   42490
193     195                            Apple iPhone 16 (256GB)   79900
194     196                     Realme GT 7 (12GB RAM + 512GB)   48999
195     197                              Samsung Galaxy F36 5G   22450
196     198                              Samsung Galaxy M56 5G   31999
197     199                                   Realme P3 Pro 5G   20999
198     200                                    OPPO F33 Pro 5G   39999
199     201                                    Poco X8 Pro Max   48999
200     202                 Realme P4 Pro 5G (8GB RAM + 256GB)   30999
201     203                                 Google Pixel 8 Pro   49999
202     204                             OnePlus Nord CE 6 Lite   28065
203     205                   OnePlus 15 5G (16GB RAM + 512GB)   93999
204     206                            Apple iPhone 17 (512GB)  102900
205     207                                       Realme GT 7T   32999
206     208                 Realme GT 8 Pro (16GB RAM + 512GB)   78999
207     209                                        Vivo V40 5G   34999
208     210                                         Realme 12X   11999
209     211                              Samsung Galaxy M36 5G   21999
210     212      Motorola Edge 60 Fusion 5G (12GB RAM + 256GB)   29499
211     213                             Infinix Note 60 Pro 5G   33949
212     214                      Vivo T5x 5G (8GB RAM + 128GB)   29203
213     215                                   Apple iPhone 17e   64900
214     216                    OnePlus N6 5G (6GB RAM + 128GB)   26999
215     217                              Samsung Galaxy A27 5G   32950
216     218                        iQOO 15R (12GB RAM + 256GB)   59999
217     219                Motorola Signature (16GB RAM + 1TB)   69999
218     220            Samsung Galaxy A17 5G (8GB RAM + 128GB)   23499
219     221                       Poco M7 5G (8GB RAM + 128GB)   13499
220     222                        Boltt Evo (6GB RAM + 128GB)   10999
221     223                               Realme Narzo 100x 5G   19859
222     224            Samsung Galaxy S25 FE (8GB RAM + 256GB)   65999
223     225                              Samsung Galaxy A37 5G   38999
224     226        Samsung Galaxy S26 Ultra (12GB RAM + 512GB)  150999
225     227                     Boltt Ace 5G (6GB RAM + 128GB)   13999
226     228                 Oppo F31 Pro 5G (12GB RAM + 256GB)   29999
227     229                              Samsung Galaxy F17 5G   17999
228     230           Samsung Galaxy F70e 5G (6GB RAM + 128GB)   18650
229     231                                  Google Pixel 8 5G   37999
230     232              Realme GT 2 Pro 5G (12GB RAM + 256GB)   27900
231     233                                    Vivo T5 Lite 5G   20499
232     234                     Vivo V70 5G (12GB RAM + 256GB)   64999
233     235                                   Realme 16 Pro 5G   37999
234     236                                      Poco M8 Power   24390
235     237                                Xiaomi Redmi 15C 5G   17499
236     238                                   Vivo X300 Pro 5G  119999
237     239                                  Infinix GT 30 Pro   31999
238     240                      Samsung Galaxy S24 FE (256GB)   45999
239     241                              Samsung Galaxy A35 5G   29990
240     242                          Poco X8 (8GB RAM + 256GB)   35999
241     243                                       Xiaomi 17 5G   89999
242     244                              Samsung Galaxy F15 5G   13499
243     245                         Motorola Moto G37 Power 5G   17132
244     246                       Vivo S2 5G (8GB RAM + 256GB)   44999
245     247                                          iQOO Z11x   27999
246     248            Samsung Galaxy A17 5G (8GB RAM + 256GB)   27999
247     249                                        OnePlus N6x   20999
248     250                                          Vivo V60e   34999
249     251                                   Apple iPhone Air  101900
250     252            Motorola Edge 60 Pro (16GB RAM + 512GB)   40999
251     253            Samsung Galaxy A56 5G (8GB RAM + 256GB)   38968
252     254                               Lava Virat V1 Pro 5G   15999
253     255                      Vivo T5x 5G (8GB RAM + 256GB)   32889
254     256          Samsung Galaxy S26 Ultra (16GB RAM + 1TB)  180999
255     257                                      Oppo Reno 15c   41999
256     258                                        Oppo F31 5G   26999
257     259                                       Vivo Y400 5G   31991
258     260                                    Vivo T4 Lite 5G   18899
259     261                                 Nothing Phone 3 5G   79999
260     262                                    Google Pixel 9A   49699
261     263             OnePlus Nord CE 6 5G (8GB RAM + 256GB)   41999
262     264                                 Tecno Pova Curve 2   26499
263     265             Xiaomi Redmi Note 14 (8GB RAM + 256GB)   24999
264     266                            Samsung Galaxy Z Flip 3   41499
265     267                                       Realme 16 5G   36999
266     268            Samsung Galaxy A07 5G (6GB RAM + 128GB)   21499
267     269                         iQOO 15 (16GB RAM + 512GB)   93999
268     270                                     Oppo K13 Turbo   33998
269     271                                        Realme GT 7   41999
270     272                            Samsung Galaxy S25 Plus   79999
271     273               Infinix Note 30 5G (8GB RAM + 256GB)   15999
272     274     Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB)  254999
273     275                               Tecno Camon 50 Ultra   39998
274     276                            Motorola Moto G77 Power   25598
275     277      Motorola Moto G67 Power 5G (12GB RAM + 256GB)   27440
276     278                      Poco M8x 5G (6GB RAM + 128GB)   21648
277     279                                Xiaomi Redmi 15A 5G   16400
278     280      Xiaomi Redmi Note 15 Pro 5G (8GB RAM + 256GB)   33999
279     281                               Oppo F31 Pro Plus 5G   32999
280     282                               Motorola Edge 70 Max   53789

In [81]:
processor_rows = set((619 , 880))
ram_rows = set((284,501,880))
battery_rows = set((880,))
display_rows = set((880,))
camera_rows = set((4,26,43,103,136,145,147,266,274,306,311,327,405,435,452,467,468,484,520,539,551,560,606,619,630,654,663,673,674,675,678,691,726,743,744,755,756,766,771,796,802,812,825,880,936,1007))

In [82]:
df1[df1['index'].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
282,284,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
499,501,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0,No FM Radio,Bluetooth
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [83]:
temp_df = df1[df1['index'].isin(processor_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0,No FM Radio,Bluetooth
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth

In [84]:
# processor_row
# 619 rows
temp_df.iloc[0, 7:] = temp_df.iloc[0, 5:-2].values

In [85]:
temp_df.iloc[0, 5:7] = None

In [86]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,Series 30 12,No FM Radio,Bluetooth

In [87]:
# row 880
temp_df.iloc[1,6:] = temp_df.iloc[1,5:-1]

In [88]:
temp_df.iloc[1, (5,10,11)] = None

In [89]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None

In [90]:
df1[df1['index'].isin([619, 880])] = temp_df

In [91]:
# ram rows

df1[df1['index'].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
282,284,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",128 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
499,501,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Bionic A18, Hexa Core, 4.04 GHz Processor",256 GB inbuilt,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None

In [92]:
# battery row
# display row

# already fixed

In [93]:
# camera

temp_df = df1[df1['index'].isin(camera_rows)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display","Foldable Display, Dual Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",Dual Display,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...","Foldable Display, Dual Display",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...","Foldable Display, Dual Display",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...","Foldable Display, Dual Display",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...","Foldable Display, Dual Display",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [94]:
temp_df.shape
mask = ~temp_df['index'].isin([619, 880])

temp_df.loc[mask, temp_df.columns[9]] = temp_df.loc[mask, temp_df.columns[10]]

In [95]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
617,619,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [96]:
df1[df1['index'].isin(camera_rows)] = temp_df

In [97]:
# see all rows in pandas

# pd.set_option('display.max_rows', None)

pd.reset_option('display.max_rows')

In [98]:
# card row

temp_df = df1[df1['card'].str.contains('Android' , na=False)]
temp_df['card'].value_counts()

card
Android v15      79
Android v16      69
Android v14      30
Android v12      19
Android v13      10
Android v17       7
Android v11       4
Android v10       4
Android           2
Android v12.0     2
Android v13.0     1
Android v14.0     1
Name: count, dtype: int64

In [99]:
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
5,7,Motorola Edge 70 Fusion,27695,70.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 7s Gen4, Octa Core, 2.7 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 68W Fast Charging,"6.8 inches, 1272 x 2772 px, 144 Hz Display wit...",50 MP + 13 MP + Dedicated 3-in-1 light sensor ...,Android v16,No FM Radio
9,11,Poco X7 Pro 5G,23999,70.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Dimensity 8400 Ultra, Octa Core, 3.25 GHz Proc...","8 GB RAM, 256 GB inbuilt",6550 mAh Battery with 90W Fast Charging,"6.67 inches, 1220 x 2712 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 20 MP Front Camera,Android v15,No FM Radio
12,14,OnePlus Nord 5 5G,33999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8s Gen3, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",6800 mAh Battery with 80W Fast Charging,"6.83 inches, 1272 x 2800 px, 144 Hz Display wi...",50 MP + 8 MP Dual Rear & 50 MP Front Camera,Android v15,No FM Radio
15,17,Realme P3 5G,15999,61.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","6 GB RAM, 128 GB inbuilt",6000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
20,22,Oppo K13 (8GB RAM + 256GB),23999,63.0,"Dual Sim, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 6 Gen4, Octa Core, 2.3 GHz Processor","8 GB RAM, 256 GB inbuilt",7000 mAh Battery with 80W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,Android v15,No FM Radio
...,...,...,...,...,...,...,...,...,...,...,...,...
971,973,Asus ROG Phone 5s Pro 5G,79999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 888+, Octa Core, 2.9 GHz Processor","18 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 144 Hz Display",64 MP + 13 MP + 5 MP Triple Rear & 24 MP Front...,Android v11,No FM Radio
972,974,iQOO 9 5G (12GB RAM + 256GB),50650,68.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Snapdragon 888+, Octa Core, 2.9 GHz Processor","12 GB RAM, 256 GB inbuilt",4350 mAh Battery with 120W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",48 MP + 13 MP + 13 MP Triple Rear & 16 MP Fron...,Android v12,No FM Radio
974,976,Xiaomi Mi 11T Pro 5G,33376,71.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 888 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
975,977,Xiaomi 11T Pro 5G (12GB RAM + 256GB),37758,71.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
987,989,Realme X7 Pro,29999,64.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 1000+, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 65W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP Quad Rear & 32 MP Front Camera,Android v10,No FM Radio

In [100]:
temp_df.iloc[:, 11] = temp_df.iloc[:, 10].values

In [101]:
temp_df.iloc[:, 10] = "Memory Card Not Supported"

In [102]:
df1[df1['card'].str.contains('Android' , na=False)] = temp_df

In [103]:
temp_df = df1[df1['card'].str.contains('MP' , na=False)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
101,103,Samsung Galaxy Z Fold 8 5G,174999,92.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
134,136,Samsung Galaxy Z Fold 8 Ultra,194999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
272,274,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
304,306,Google Pixel 11 Pro Fold,186999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",Tensor G6,"16 GB RAM, 512 GB inbuilt",4806 mAh Battery with Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v17
309,311,Samsung Galaxy Z Fold 7,154999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
403,405,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
450,452,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
465,467,Samsung Galaxy Z Fold 4,89599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
558,560,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,50 MP Dual Rear & 8 MP Front Camera,Memory Card (Hybrid)
652,654,Samsung Galaxy Z Fold 6,139900,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen 3, Octa Core, 3.39 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1856 x 2160 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v14
661,663,Samsung Galaxy Z Fold 4,86599,84.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
672,674,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","16 GB RAM, 1 TB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
673,675,Samsung Galaxy Z Fold 8 Ultra (12GB RAM + 512GB),214999,95.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Android v17
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
741,743,Vivo X Fold 5 5G,139999,92.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 20 MP + 20...,Android v15
742,744,Samsung Galaxy Z Fold 7 (12GB RAM + 512GB),165703,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 512 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"8 inches, 1968 x 2184 px, 120 Hz Display with ...",200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,200 MP + 12 MP + 10 MP Triple Rear & 10 MP + 1...,Android v16
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
794,796,Samsung Galaxy Z Fold 8 (12GB RAM + 512GB),194999,93.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...","12 GB RAM, 512 GB inbuilt",4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Android v17
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported
810,812,Google Pixel 10 Pro Fold,162999,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Tensor G5, Octa Core, 3.78 GHz Processor","16 GB RAM, 256 GB inbuilt",5015 mAh Battery with 30W Fast Charging,"8 inches, 2076 x 2152 px, 120 Hz Display with ...",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v16
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
913,915,Google Pixel 9 Pro Fold,132900,85.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Tensor G4, Octa Core, 3.1 GHz Processor","16 GB RAM, 256 GB inbuilt",4650 mAh Battery with Fast Charging,"8.03 inches, 2152 x 2076 px, 120 Hz Display wi...","Foldable Display, Dual Display",48 MP + 10.8 MP + 10.5 MP Triple Rear & 10 MP ...,Android v14
934,936,Samsung Galaxy Z Fold 5,154999,86.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.36 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v13
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported

In [104]:
temp_df.iloc[:, 10] = "Memory Card Not Supported"

In [105]:
df1[df1['card'].str.contains('MP' , na=False)] = temp_df

In [106]:
df1['card'].value_counts()

card
Memory Card Not Supported             480
Memory Card (Hybrid), upto 1 TB       101
Memory Card Supported, upto 1 TB       78
Memory Card (Hybrid), upto 2 TB        75
Memory Card (Hybrid)                   64
Memory Card Supported                  42
Memory Card Supported, upto 2 TB       36
Memory Card Supported, upto 256 GB     13
Memory Card Supported, upto 512 GB     10
Memory Card (Hybrid), upto 1.5 TB       7
Memory Card (Hybrid), upto 128 GB       5
Memory Card (Hybrid), upto 256 GB       4
Memory Card Supported, upto 128 GB      3
Memory Card (Hybrid), upto 512 GB       2
Name: count, dtype: int64

In [107]:
df1['os'].value_counts()

os
Android v16                  284
Android v15                  256
Android v14                  107
Android v12                   58
Android v13                   53
Android v11                   40
Memory Card Not Supported     24
Android v17                   16
Android v10                   12
iOS v26                       11
iOS v27                        8
Android v9.0 (Pie)             8
iOS v18                        7
iOS v17                        5
Android v10.0                  5
No FM Radio                    3
Android v8.1 (Oreo)            3
iOS v26.3                      2
v60                            2
Android                        2
Android 15 Go                  2
Android v12.0                  2
Android v14.0                  2
Android 15 Go Edition          2
v30                            1
iOS v15                        1
Android v13.0                  1
Memory Card (Hybrid)           1
Bluetooth                      1
iOS v11                        1
Name: count, dtype: int64

In [108]:
temp_df = df1[~df1['os'].str.contains('Android|iOS' , case=False,na=False)]
temp_df

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
24,26,Apple iPhone Duo (2TB),449900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 2 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
41,43,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 1 TB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
145,147,Apple iPhone Duo (512GB),324900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 512 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,Memory Card Not Supported
264,266,Samsung Galaxy Z Flip 3,41499,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
325,327,Motorola Razr Fold,149999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
333,335,Ringme Bold S170 Air Pro,13000,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Dual Core, 1.7 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.61 inches, 128 x 160 px Display with Punch Hole",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",v30
433,435,Samsung Galaxy Z Flip 4 (8GB RAM + 256GB),51999,72.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
466,468,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
482,484,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
518,520,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
537,539,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
549,551,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
604,606,Vivo X Fold 3 Pro,124999,95.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","16 GB RAM, 512 GB inbuilt",5700 mAh Battery with 100W Fast Charging,"8.03 inches, 2200 x 2480 px, 120 Hz Display wi...",64 MP + 50 MP + 50 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
628,630,Lava Blaze Duo 3 5G,24999,59.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Dimensity 7060, Octa Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 33W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Memory Card (Hybrid)
671,673,Samsung Galaxy Z Flip 8 5G,114999,89.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
676,678,Motorola Razr Fold FIFA World Cup 26 Edition,169999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
689,691,Samsung Galaxy Z Flip 7 5G,95999,88.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2500, Deca Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
710,712,Peace i Ultra,10999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",Single Core Processor,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.61 inches, 720 x 1640 px Display with Punch ...",20 MP Rear & 8 MP Front Camera,Memory Card Supported,v60
722,724,Peace Nova 17 Pro 4G (6GB RAM + 64GB),9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
724,726,Ai+ Nova Flip,49999,74.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4325 mAh Battery with Fast Charging,"6.9 inches, 2790 x 1188 px Display with Punch ...",50 MP + 2 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
753,755,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","16 GB RAM, 1 TB inbuilt",4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
754,756,Samsung Galaxy Z Flip 6 5G,71999,84.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen3, Octa Core, 3.3 GHz Processor","12 GB RAM, 256 GB inbuilt",4000 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
764,766,Tecno Phantom V Flip,39999,75.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi","Dimensity 8050, Octa Core, 3 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"6.9 inches, 1080 x 2640 px, 144 Hz Display wit...",64 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
769,771,Samsung Galaxy Z Flip 5,63890,76.0,"Single Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi","Snapdragon 8 Gen 2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
793,795,Ringme Bold 16 Pro,9899,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",Dual Core Processor,"4 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.61 inches, 128 x 160 px Display",13 MP Rear Camera,"Memory Card (Hybrid), upto 128 GB",Bluetooth
800,802,Motorola Razr Fold (16GB RAM + 512GB),159999,98.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"8.09 inches, 2232 x 2484 px, 120 Hz Display wi...",50 MP + 50 MP + 50 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,Memory Card Not Supported
808,810,Peace Nova 17 Pro 4G (6GB RAM + 128GB),9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
823,825,Motorola Razr 50,64990,80.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Dimensity 7300X, Octa Core, 2.5 GHz Processor","8 GB RAM, 256 GB inbuilt",4200 mAh Battery with 33W Fast Charging,"6.9 inches, 1080 x 2640 px, 120 Hz Display wit...",50 MP + 13 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
870,872,Peace Nova 13,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio, Single Core, 1.7 GHz Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.85 inches, 1640 x 720 px Display with Punch ...",20 MP Rear Camera,"Memory Card Supported, upto 128 GB",v60
878,880,Ringme Bold S16,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",None,"3 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.85 inches, 128 x 160 px Display",13 MP Rear Camera,None,None
888,890,Peace Nova 17 Pro 4G,9997,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi","MTK6739, Single Core Processor","4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card (Hybrid), upto 128 GB",No FM Radio
1005,1007,Samsung Galaxy Z Flip 8 5G (12GB RAM + 512GB),134999,90.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Exynos 2600, Deca Core, 3.8 GHz Processor","12 GB RAM, 512 GB inbuilt",4300 mAh Battery with 25W Fast Charging,"6.9 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported

In [109]:
temp_df.iloc[:,11] = None

In [110]:
df1[~df1['os'].str.contains('Android|iOS' , case=False,na=False)] = temp_df

In [111]:
df1['os'].value_counts()

os
Android v16              284
Android v15              256
Android v14              107
Android v12               58
Android v13               53
Android v11               40
Android v17               16
Android v10               12
iOS v26                   11
Android v9.0 (Pie)         8
iOS v27                    8
iOS v18                    7
iOS v17                    5
Android v10.0              5
Android v8.1 (Oreo)        3
Android v12.0              2
Android                    2
Android 15 Go              2
iOS v26.3                  2
Android v14.0              2
Android 15 Go Edition      2
iOS v15                    1
Android v13.0              1
iOS v11                    1
Name: count, dtype: int64

In [112]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 921 entries, 0 to 1011
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      921 non-null    int64
 1   model      921 non-null    object
 2   price      921 non-null    int64
 3   rating     786 non-null    float64
 4   sim        921 non-null    object
 5   processor  919 non-null    object
 6   ram        920 non-null    object
 7   battery    921 non-null    object
 8   display    921 non-null    object
 9   camera     921 non-null    object
 10  card       920 non-null    object
 11  os         888 non-null    object
dtypes: float64(1), int64(2), object(9)
memory usage: 93.5+ KB

In [113]:
df1['camera'].value_counts()

camera
50 MP + 2 MP Dual Rear & 8 MP Front Camera             58
50 MP + 2 MP Dual Rear & 16 MP Front Camera            34
50 MP + 8 MP Dual Rear & 32 MP Front Camera            33
50 MP Dual Rear & 8 MP Front Camera                    31
50 MP + 8 MP Dual Rear & 16 MP Front Camera            27
                                                       ..
64 MP Quad Rear & 16 MP Front Camera                    1
48 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera     1
13 MP Quad Rear & 8 MP Front Camera                     1
12 MP Quad Rear & 13 MP Front Camera                    1
16 MP + 5 MP Dual Rear & 25 MP Front Camera             1
Name: count, Length: 189, dtype: int64

#Cleaning Part Two

# Here we solve the tidiness issue and more cleaning

In [114]:
df1.head(3)

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None

In [115]:
brand_names = df1['model'].str.split().str.get(0).str.lower()

In [116]:
df1.insert(1,'brand_name',brand_names)

In [117]:
df1[df1['brand_name'] == 'moto']

,index,brand_name,model,price,rating,sim,processor,ram,battery,display,camera,card,os
128,130,moto,Moto G57 Power,20999,57.0,"Dual Sim, 5G, eSIM, Wi-Fi","Snapdragon 6s Gen4, Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",7000 mAh Battery with 33W Fast Charging,"6.72 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP Dual Rear & 8 MP Front Camera,Memory Card Not Supported,Android v16

In [118]:
# moto is actually motorola so we have to replace it

In [119]:
df1['brand_name'] = df1['brand_name'].replace('moto' , 'motorola')

In [120]:
df1['brand_name'].value_counts()

brand_name
samsung     159
realme      142
oppo         87
vivo         71
xiaomi       70
motorola     64
poco         53
oneplus      42
apple        39
iqoo         25
google       22
tecno        21
lava         21
infinix      20
nothing      16
ai+          15
peace        11
itel          9
ringme        8
alcatel       5
boltt         5
hmd           3
wobble        2
coolpad       2
mtr           2
philips       2
honor         2
samaung       1
acer          1
asus          1
Name: count, dtype: int64

In [121]:
# a phone has mis spelled samsung

In [122]:
df1['brand_name'] = df1['brand_name'].replace('samaung' , 'samsung')

In [123]:
df1['brand_name'].value_counts()

brand_name
samsung     160
realme      142
oppo         87
vivo         71
xiaomi       70
motorola     64
poco         53
oneplus      42
apple        39
iqoo         25
google       22
tecno        21
lava         21
infinix      20
nothing      16
ai+          15
peace        11
itel          9
ringme        8
boltt         5
alcatel       5
hmd           3
coolpad       2
philips       2
mtr           2
wobble        2
honor         2
acer          1
asus          1
Name: count, dtype: int64

In [124]:
df1.head()

,index,brand_name,model,price,rating,sim,processor,ram,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi","Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [125]:
has_5g = df1['sim'].str.contains('5G' , case=False, na=False)
has_nfc = df1['sim'].str.contains('NFC' , case=False, na=False)
has_ir_blaster = df1['sim'].str.contains('IR Blaster' , case=False, na=False)

In [126]:
df1.insert(6,'has_5g',has_5g)
df1.insert(7,'has_nfc',has_nfc)
df1.insert(8,'has_ir_blaster',has_ir_blaster)

In [127]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,ram,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor","12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [128]:
# wroking on processor column

In [129]:
# see all rows in pandas

pd.set_option('display.max_rows', None)

# pd.reset_option('display.max_rows')

In [130]:
processor_name = df1['processor'].str.split(',').str.get(0).str.strip()

In [131]:
num_cores = df1['processor'].str.split(',').str.get(1)

In [132]:
processor_speed = df1['processor'].str.split(',').str.get(2)

In [133]:
df1.insert(10,'processor_name',processor_name)
df1.insert(11,'num_cores',num_cores)
df1.insert(12,'processor_speed',processor_speed)

In [134]:
df1.head(3)

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,Hexa Core Processor,NaN,"12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,Octa Core,2.8 GHz Processor,"8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,Hexa Core Processor,NaN,"12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None

In [135]:
df1['num_cores'] = df1['num_cores'].str.strip()

In [136]:
df1[df1['processor_name'] .str.contains('Core' , na=False , case=False)]

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
520,522,ringme,Ringme Bold 17 Pro (6GB RAM + 64GB),13000,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,"Dual Core, 1.7 GHz Processor",Dual Core,1.7 GHz Processor,NaN,"6 GB RAM, 64 GB inbuilt",4000 mAh Battery,"6.68 inches, 1640 x 720 px Display",13 MP Rear Camera,Memory Card Not Supported,Android v12
670,672,ringme,Ringme Bold 17 Pro,9753,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,"Dual Core, 1.7 GHz Processor",Dual Core,1.7 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",4000 mAh Battery,"6.68 inches, 1640 x 720 px Display",13 MP Rear Camera,Memory Card Not Supported,Android v12
710,712,peace,Peace i Ultra,10999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Single Core Processor,Single Core Processor,NaN,NaN,"6 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.61 inches, 720 x 1640 px Display with Punch ...",20 MP Rear & 8 MP Front Camera,Memory Card Supported,None
713,715,ringme,Ringme Bold 26 Ultra,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Dual Core Processor,Dual Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery,"6.79 inches, 1640 x 720 px Display with Punch ...",13 MP Rear Camera,Memory Card Not Supported,Android v12
714,716,itel,itel Zeno 100 Lite,8599,NaN,"Dual Sim, 4G, Wi-Fi, IR Blaster",False,False,True,Octa Core Processor,Octa Core Processor,NaN,NaN,"2 GB RAM, 64 GB inbuilt",5000 mAh Battery with Fast Charging,"6.6 inches, 720 x 1612 px, 90 Hz Display with ...",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v15
791,793,peace,Peace Honor 40 Mini,7999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Single Core Processor,Single Core Processor,NaN,NaN,"4 GB RAM, 32 GB inbuilt",2000 mAh Battery,"4.5 inches, 412 x 960 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Not Supported,Android
793,795,ringme,Ringme Bold 16 Pro,9899,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,Dual Core Processor,Dual Core Processor,NaN,NaN,"4 GB RAM, 64 GB inbuilt",3900 mAh Battery,"6.61 inches, 128 x 160 px Display",13 MP Rear Camera,"Memory Card (Hybrid), upto 128 GB",None
854,856,samsung,Samsung Galaxy A13,15650,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,"Octa Core, 2 GHz Processor",Octa Core,2 GHz Processor,NaN,"4 GB RAM, 64 GB inbuilt",5000 mAh Battery with 25W Fast Charging,"6.6 inches, 1080 x 2408 px Display with Water ...",50 MP Quad Rear & 8 MP Front Camera,"Memory Card Supported, upto 1 TB",Android v12

In [137]:
# shifting rows by one , where in processor column

In [138]:
cols = ['processor_name', 'num_cores', 'processor_speed']

mask = df1[cols[0]].str.contains('Core', na=False , case=False)

df1.loc[mask, cols] = df1.loc[mask, cols].shift(axis=1)

In [139]:
df1['num_cores'] = df1['num_cores'].str.strip()

In [140]:
df1['num_cores'].value_counts()

num_cores
Octa Core                797
Octa Core Processor       33
Hexa Core Processor       25
Deca Core                 19
Hexa Core                 14
Single Core                5
Single Core Processor      5
Dual Core                  4
Dual Core Processor        2
Nine-Cores                 1
Nine Cores                 1
Nine Core                  1
512 MHz Processor          1
Quad Core                  1
Name: count, dtype: int64

In [141]:
df1['num_cores'] = df1['num_cores'].str.replace('Octa Core Processor' , 'Octa Core')
df1['num_cores'] = df1['num_cores'].str.replace('Hexa Core Processor' , 'Hexa Core')
df1['num_cores'] = df1['num_cores'].str.replace('Single Core Processor' , 'Single Core')
df1['num_cores'] = df1['num_cores'].str.replace('Dual Core Processor' , 'Dual Core')
df1['num_cores'] = df1['num_cores'].str.replace('Nine-Cores' , 'Nine Core')
df1['num_cores'] = df1['num_cores'].str.replace('Nine Cores' , 'Nine Core')

In [142]:
df1[df1['num_cores'] == '512 MHz Processor']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,num_cores,processor_speed,ram,battery,display,camera,card,os
686,688,mtr,MTR M16 Pro,6400,NaN,"Dual Sim, 4G, Wi-Fi",False,False,False,"Helio, 512 MHz Processor",Helio,512 MHz Processor,NaN,"3 GB RAM, 32 MB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display with Punch Hole",5 MP Rear Camera,Memory Card Not Supported,Android v13.0

In [143]:
df1['num_cores'] = df1['num_cores'].str.replace('512 MHz Processor' , 'Quad Core')

In [144]:
# processor brand

In [145]:
processor_brand = df1['processor_name'].str.split(' ').str.get(0).str.lower()

In [146]:
df1.insert(11,'processor_brand',processor_brand)

In [147]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8 GHz Processor,"8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",Dimensity 7050,dimensity,Octa Core,2.6 GHz Processor,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [148]:
# processor speed

In [149]:
df1['processor_speed'] = df1['processor_speed'].str.strip().str.split().str.get(0).astype(float)

In [150]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,processor_name,processor_brand,num_cores,processor_speed,ram,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",Snapdragon 7 Gen4,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",Apple A20 Pro,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",Dimensity 7050,dimensity,Octa Core,2.6,"8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [151]:
# Working ram column

In [152]:
ram_capacity = df1['ram'].str.strip().str.split(',').str.get(0).str.split().str.get(0)

In [153]:
df1.insert(15,'ram_capacity',ram_capacity)

In [154]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,processor_brand,num_cores,processor_speed,ram,ram_capacity,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,snapdragon,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8,6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,apple,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,dimensity,Octa Core,2.6,"8 GB RAM, 128 GB inbuilt",8,5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [155]:
internal_memory = df1['ram'].str.strip().str.split(',').str.get(1).str.split().str.get(0)

In [156]:
df1.insert(16,'internal_memory',internal_memory)

In [157]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8,256,6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,Octa Core,2.6,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [158]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 921 entries, 0 to 1011
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            921 non-null    int64
 1   brand_name       921 non-null    object
 2   model            921 non-null    object
 3   price            921 non-null    int64
 4   rating           786 non-null    float64
 5   sim              921 non-null    object
 6   has_5g           921 non-null    bool
 7   has_nfc          921 non-null    bool
 8   has_ir_blaster   921 non-null    bool
 9   processor        919 non-null    object
 10  processor_name   911 non-null    object
 11  processor_brand  911 non-null    object
 12  num_cores        909 non-null    object
 13  processor_speed  843 non-null    float64
 14  ram              920 non-null    object
 15  ram_capacity     920 non-null    object
 16  internal_memory  918 non-null    object
 17  battery          921 non-null    object
 18  display          921 non-null    object
 19  camera           921 non-null    object
 20  card             920 non-null    object
 21  os               888 non-null    object
dtypes: bool(3), float64(2), int64(2), object(15)
memory usage: 146.6+ KB

In [159]:
df1['ram_capacity'].value_counts()

ram_capacity
8      350
12     188
4      171
6      148
16      36
3       22
2        2
128      1
256      1
18       1
Name: count, dtype: int64

In [160]:
df1[df1['ram_capacity'] == '128']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
282,284,apple,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",...,Hexa Core,4.04,128 GB inbuilt,128,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

In [161]:
df1[df1['ram_capacity'] == '256']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
499,501,apple,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",...,Hexa Core,4.04,256 GB inbuilt,256,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18

In [162]:
df1['ram_capacity'] = df1['ram_capacity'].replace('128', '8')
df1['ram_capacity'] = df1['ram_capacity'].replace('256', '8')

In [163]:
df1['internal_memory'].value_counts()

internal_memory
128    396
256    309
64     106
512     77
32      13
1       13
2        3
16       1
Name: count, dtype: int64

In [164]:
df1[df1['internal_memory'] == '1']

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
41,43,apple,Apple iPhone Duo (1TB),374900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 1 TB inbuilt",12,1,5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
63,65,apple,Apple iPhone 18 Pro Max (1TB),254900,88.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 1 TB inbuilt",12,1,5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
106,108,apple,Apple iPhone 18 Pro (1TB),239900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 1 TB inbuilt",12,1,4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
217,219,motorola,Motorola Signature (16GB RAM + 1TB),69999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, Wi-Fi",True,True,False,"Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor",...,Octa Core,3.80,"16 GB RAM, 1 TB inbuilt",16,1,5200 mAh Battery with 90W Fast Charging,"6.8 inches, 1264 x 2780 px, 165 Hz Display wit...",50 MP + 50 MP + 50 MP Triple Rear & 50 MP Fron...,Memory Card Not Supported,Android v16
254,256,samsung,Samsung Galaxy S26 Ultra (16GB RAM + 1TB),180999,97.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...",...,Octa Core,4.74,"16 GB RAM, 1 TB inbuilt",16,1,5000 mAh Battery with 60W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v16
272,274,samsung,Samsung Galaxy Z Fold 8 Ultra (16GB RAM + 1TB),254999,98.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite Gen 5 For Galaxy, Octa Core...",...,Octa Core,4.74,"16 GB RAM, 1 TB inbuilt",16,1,5000 mAh Battery with 45W Fast Charging,"8 inches, 2256 x 2504 px, 120 Hz Display with ...",200 MP + 50 MP + 10 MP Triple Rear & 10 MP + 1...,Memory Card Not Supported,Android v17
403,405,samsung,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...",...,Octa Core,4.74,"16 GB RAM, 1 TB inbuilt",16,1,4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Memory Card Not Supported,Android v17
411,413,apple,Apple iPhone 17 Pro Max (1TB),183990,83.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A19 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 1 TB inbuilt",12,1,4832 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v26
641,643,apple,Apple iPhone 17 Pro (1TB),172900,76.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A19 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 1 TB inbuilt",12,1,3988 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v26
649,651,samsung,Samsung Galaxy S25 Ultra (12GB RAM + 1TB),165999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...",...,Octa Core,4.47,"12 GB RAM, 1 TB inbuilt",12,1,5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
672,674,samsung,Samsung Galaxy Z Fold 8 (16GB RAM + 1TB),234999,94.0,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi",True,True,False,"Snapdragon 8 Elite Gen 5 for Galaxy, Octa Core...",...,Octa Core,4.74,"16 GB RAM, 1 TB inbuilt",16,1,4800 mAh Battery with 45W Fast Charging,"7.6 inches, 1828 x 2448 px, 120 Hz Display wit...",50 MP + 50 MP Dual Rear & 10 MP + 10 MP Dual F...,Memory Card Not Supported,Android v17
753,755,oneplus,OnePlus Open 5G Apex Edition,149999,90.0,"Dual Sim, 5G, VoLTE, NFC, Wi-Fi, IR Blaster",True,True,True,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor",...,Octa Core,3.20,"16 GB RAM, 1 TB inbuilt",16,1,4805 mAh Battery with 67W Fast Charging,"7.82 inches, 2268 x 2440 px, 120 Hz Display wi...",64 MP + 48 MP + 48 MP Triple Rear & 32 MP + 20...,Memory Card Not Supported,None
812,814,apple,Apple iPhone Air (1TB),139990,67.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A19 Pro, Hexa Core Processor",...,Hexa Core,NaN,"8 GB RAM, 1 TB inbuilt",8,1,3149 mAh Battery with Fast Charging,"6.5 inches, 1260 x 2736 px Display with Dynami...",48 MP Rear & 18 MP Front Camera,Memory Card Not Supported,iOS v26

In [165]:
# we have to replace the TB values in gb

In [166]:
df1['internal_memory'] = df1['internal_memory'].replace('1', '1024')
df1['internal_memory'] = df1['internal_memory'].replace('2', '2048')

In [167]:
df1[df1['internal_memory'].isnull()]

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
282,284,apple,Apple iPhone 16 Plus,79900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",...,Hexa Core,4.04,128 GB inbuilt,8,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
499,501,apple,Apple iPhone 16 Plus (256GB),89900,70.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Bionic A18, Hexa Core, 4.04 GHz Processor",...,Hexa Core,4.04,256 GB inbuilt,8,NaN,4674 mAh Battery with Fast Charging,"6.7 inches, 1290 x 2796 px Display with Dynami...",48 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v18
617,619,peace,Peace i17 Air,9999,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",False,False,False,None,...,None,NaN,None,None,None,5000 mAh Battery,"6.56 inches, 1640 x 720 px Display",20 MP Rear & 8 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v14.0

In [168]:
df1.loc[282 , 'internal_memory'] = 128
df1.loc[499 , 'internal_memory'] = 256

In [169]:
df1.loc[617 , 'internal_memory'] = 64
df1.loc[617 , 'ram_capacity'] = 6
df1.loc[617 , 'ram'] = '6 GB RAM, 64 GB inbuilt'

In [170]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 921 entries, 0 to 1011
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   index            921 non-null    int64
 1   brand_name       921 non-null    object
 2   model            921 non-null    object
 3   price            921 non-null    int64
 4   rating           786 non-null    float64
 5   sim              921 non-null    object
 6   has_5g           921 non-null    bool
 7   has_nfc          921 non-null    bool
 8   has_ir_blaster   921 non-null    bool
 9   processor        919 non-null    object
 10  processor_name   911 non-null    object
 11  processor_brand  911 non-null    object
 12  num_cores        909 non-null    object
 13  processor_speed  843 non-null    float64
 14  ram              921 non-null    object
 15  ram_capacity     921 non-null    object
 16  internal_memory  921 non-null    object
 17  battery          921 non-null    object
 18  display          921 non-null    object
 19  camera           921 non-null    object
 20  card             920 non-null    object
 21  os               888 non-null    object
dtypes: bool(3), float64(2), int64(2), object(15)
memory usage: 178.9+ KB

In [171]:
df1['ram_capacity'] = df1['ram_capacity'].astype(int)

In [172]:
df1['internal_memory'] = df1['internal_memory'].astype(int)

In [173]:
# Now solving Battery rows

In [174]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,num_cores,processor_speed,ram,ram_capacity,internal_memory,battery,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,4056 mAh Battery with Fast Charging,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,Octa Core,2.8,"8 GB RAM, 256 GB inbuilt",8,256,6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,5800 mAh Battery with Fast Charging,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,Hexa Core,NaN,"12 GB RAM, 256 GB inbuilt",12,256,5391 mAh Battery with Fast Charging,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,Octa Core,2.6,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with 45W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [181]:
battery_capacity = df['battery'].str.strip().str.split().str.get(0)

In [185]:
df1.insert(18,'battery_capacity',battery_capacity)

In [198]:
df1['battery'].str.split('with').str.get(1).str.strip().str.split().head()

0         [Fast, Charging]
1    [90W, Fast, Charging]
2         [Fast, Charging]
3         [Fast, Charging]
4    [45W, Fast, Charging]
Name: battery, dtype: object

In [204]:
fast_charging = df1['battery'].str.extract(r'(\d+)\s*W\s*Fast Charging', expand=False).fillna(df1['battery'].str.contains('Fast Charging', case=False, na=False).map({True: 0, False: -1})).astype(int)

In [207]:
df1.insert(19,'fast_charging',fast_charging)

In [214]:
df1['fast_charging'].astype(int)

0         0
1        90
2         0
3         0
4        45
5        68
6         0
7        44
8        45
9        90
10       25
11      100
12       80
13       18
14       90
15       45
16        0
17       45
18       90
19       33
20       80
21       68
22       90
23       25
24        0
25       45
26       80
27       80
28       80
29       60
30       45
31        0
32       90
33       68
34       80
35       80
36       44
37       18
38       90
39       45
40      120
41        0
42       45
43       68
44       90
45        0
46       25
47       44
48        0
49       25
50        0
51       45
52       45
53       44
54       80
55       18
56       67
57       25
58       45
59       45
60       90
61       45
62       68
63        0
64       33
65       45
66       45
67       45
68       18
69       45
70       90
71       90
72        0
73       44
74       30
75        0
76       80
77       90
78       90
79       18
80       50
81      120
82       80
83        0
84      100
85       44
86       45
87       25
88       45
89       80
90       30
91       45
92       25
93       80
94       80
95       18
96       45
97       80
98       68
99       80
100      18
101      45
102      25
103      90
104      80
105     100
106       0
107      45
108      45
109      90
110      80
111      45
112      25
113      18
114      45
115      45
116      68
117      30
118      25
119      30
120      65
121      50
122     100
123      30
124      90
125     100
126      45
127      30
128      33
129      45
130      80
131     120
132     100
133      45
134      45
135     100
136       0
137      68
138      45
139      25
140      10
141      25
142      80
144      80
145       0
146      50
147      80
148     120
149      90
150      25
151      44
152      45
153      15
154      80
155      45
156      18
157      60
158      45
159      80
160     100
161      45
162      33
163       0
164     100
165       0
166      25
167      80
168      45
169      90
170     100
171      33
172      80
173      90
174      15
175      80
176      45
177      90
178      45
179      18
180      44
181       0
182      44
183      80
184      80
185     120
186       0
187      45
188       0
189      44
190      33
191      45
192      80
193       0
194     120
195      25
196      45
197      80
198      80
199     100
200      80
201      30
202      45
203     120
204       0
205     120
206     120
207      80
208      45
209      25
210      68
211      90
212      44
213       0
214      45
215      25
216     100
217      90
218      25
219      18
220      18
221      45
222      45
223      45
224      60
225      18
226      80
227      25
228      25
229      30
230      65
231      44
232      90
233      80
234      45
235      33
236      90
237      45
238      25
239      25
240      67
241     100
242      25
243      30
244      44
245      44
246      25
247      15
248      90
249       0
250      90
251      45
252      18
253      44
254      60
255      80
256      80
257      90
258      15
259      65
260      23
261      80
262      45
263      45
264      15
265      60
266      25
267     100
268      80
269     120
270      45
271      45
272      45
273      45
274      30
275      30
276      45
277      33
278      45
279      80
280      90
281      80
282       0
283      68
284     100
285      44
286      45
287      90
288      45
289      90
290      45
291      80
292      25
293      67
294      44
295      33
296      90
297       0
298      18
300     125
301      33
302      45
303      45
304       0
305      18
306      44
307      80
308      44
309      25
310     120
311      18
312      67
313      80
314     100
315      20
316      90
317      90
318      50
319     100
320      80
321      90
322      90
323      18
324      45
325      80
326      15
327      25
328      80
329      25
330      45
331      25
332      80
333      -1
334      10
335      90
336      18
337       0
338       0
339      15
340      80
341     100
342      33
344      45
345      15
346      90
347      25
348       0
349      25
350      25
351      45
352       0
353      45
354      25
355      45
356      80
357      80
358      45
359      45
360      45
361      80
362     120
363      15
364      80
365      90
366      50
367     100
368     100
369      45
370      80
371      25
372      33
373      30
374      90
375      45
376     100
377      45
378      45
379      45
380       0
383      33
384      80
385      44
386      18
387      80
388      27
389      80
390      33
391      66
392      33
393      90
394      90
395      90
396      15
397      44
398      44
399      80
400      80
401      25
402      10
403      45
404      45
405      90
406      45
408     100
409      45
410      33
411       0
412      33
413      15
414      25
415      67
416      33
417       0
418       0
419      10
420      45
421      80
422      18
423      15
424      50
425      50
426      25
427      80
428      60
429      25
430      45
431      90
432      33
433      25
434      45
435      44
436      45
437      80
438      15
439      45
440     100
441      80
442      80
443      33
444      60
445      25
446      25
447      45
448     100
450      25
451      44
452      15
453      45
454      15
455     100
456      45
457      80
458      80
459      25
461      15
462      80
463      80
464      25
465      25
466      25
467      44
468       0
469       0
470      90
471      45
472      80
473      80
474      80
475      80
476      67
477     125
478      67
479      45
480      -1
481      10
482      25
483      18
484      15
485      70
487      45
488      45
489      25
490      15
491      15
492      33
493      45
494      45
495      80
496      80
497      25
498      45
499       0
500      45
501      45
502      80
503      15
504     100
505      44
506      80
507      50
508      44
509      80
510      80
511      25
512      33
513      45
514       0
515     120
516      25
517      25
518      45
519      33
520      -1
521      90
522      45
523      60
524      44
525      10
526      45
527      15
528      60
529      18
530      45
531      45
533      -1
534      30
535      15
536      45
537       0
538      -1
540      45
541      80
542      25
543      15
544      25
545      80
549     100
550      25
551      30
552      68
553      80
554      33
557      44
558      45
559      80
560      10
561      18
562      25
563      90
564      67
565      25
566     120
567     100
568      67
569      15
570      25
571      67
573      44
574      25
575      80
576      45
577      44
578      45
579      15
580      80
581      33
582      33
583      15
584      45
585      15
586      60
587      15
588      80
589      80
590      33
591      33
592      45
593      25
594      45
595     120
596      18
598      80
599      80
601      15
602     120
604     100
605      67
606      90
607      45
608      18
609      30
610      67
611       0
612      45
613       0
614      80
615      30
616      10
617      -1
618      45
619       0
620      15
621      45
622      80
623      45
624      60
625      15
626      45
627      45
628      33
629      80
630      80
631      80
632      80
633      80
634      80
635      33
636      33
637      15
638      60
640      33
641       0
642      45
643      15
644      33
645      80
646      45
647      25
648      25
649      45
650      80
651      45
652      25
653     120
654      45
655      25
656      80
659      68
660      66
661      25
662      65
663      80
664      20
665      33
666       0
667      10
668      30
669      44
670      -1
671      25
672      45
673      45
674       0
675      18
676      80
677      15
678      15
679      80
680      45
681      45
682      15
683      -1
684      15
685      45
686      -1
687      -1
688      60
689      25
690      15
691      18
692      25
693      44
694      27
695      45
697      33
698      67
699      25
701      18
702      68
703      10
704      67
705       0
707      67
708      45
709      33
710      -1
711      45
713      -1
714       0
715      10
716      18
717      18
718       0
719      15
720      67
721      18
722      -1
723      45
724       0
725      15
726      10
727      15
728      45
729      10
730      25
731      45
732      15
733      45
734      15
735      25
736      60
738      10
739      15
740      15
741      80
742      25
743      18
744      33
745      25
746      18
747      44
748      15
749      45
750      45
753      67
754      25
755      67
756      44
757      25
758      67
759      67
761     120
762      10
764      45
765      68
766      25
767      68
768      25
769      25
771      25
772      10
773      25
774      25
775      80
776     120
777      60
778      33
779      -1
780      30
781      -1
782      33
783      18
784      18
785      18
786      33
787      30
788       0
789       0
791      -1
792      -1
793      -1
794      45
795      10
798       0
799      18
800      80
801      15
803      33
804      60
805      10
806       0
808      -1
810      30
812       0
814      15
815      80
817      25
819      25
820       0
821      80
822      80
823      33
824      45
825      67
826      15
827      45
828      45
829      18
832      25
834      33
835      66
837      67
838      25
840      80
842      67
843      25
844      25
845      67
846     120
847      15
848      30
849      33
850      10
851      80
852      33
853      25
854      25
855      33
856      67
857      65
858      33
859      65
860      50
861      65
862      65
863      25
865      15
866       0
867      20
868      -1
869       0
870      -1
871      10
873      18
874       0
876      10
878      -1
879      15
880       0
881      45
882      15
885      45
886      15
888      -1
890      -1
892      -1
893      -1
894       0
896       0
897      80
899      15
901      33
902      18
903       0
904      45
907      25
908      45
913       0
914      25
915      45
916      80
918      18
919      18
922      45
924      10
925      33
926      33
929      66
931      33
933      10
934      25
935      25
938      18
939      25
940      33
942      33
943      33
944      30
945      10
946      33
948      33
949       0
950      33
951      18
952      66
953       0
954     150
955      15
956      67
957      -1
958      15
959      44
960      18
961      -1
962      18
963      30
964      25
965      18
966      30
967      45
969      60
970      60
971      65
972     120
974     120
975     120
976      67
977      20
978      33
979      20
980      15
981      33
982      15
983      18
984      -1
985      25
986       0
987      65
988      -1
989      65
990      18
991      18
992      18
993       5
995      -1
996      20
997       0
998      20
999       0
1000     -1
1005     25
1011     10
Name: fast_charging, dtype: int64

In [215]:
# Fast charging

# 0 for Fast charging but Watt not mentiond

# -1 for slow charging

df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,ram,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,"12 GB RAM, 256 GB inbuilt",12,256,4056 mAh Battery with Fast Charging,4056,0,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,"8 GB RAM, 256 GB inbuilt",8,256,6500 mAh Battery with 90W Fast Charging,6500,90,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,"12 GB RAM, 256 GB inbuilt",12,256,5800 mAh Battery with Fast Charging,5800,0,"7.6 inches, 1878 x 2670 px, 120 Hz Display",48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,"12 GB RAM, 256 GB inbuilt",12,256,5391 mAh Battery with Fast Charging,5391,0,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,"8 GB RAM, 128 GB inbuilt",8,128,5000 mAh Battery with 45W Fast Charging,5000,45,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [ ]:
# Now working on display

In [ ]:
# screen_size

In [211]:
df1['display'].head()

0    6.3 inches, 1206 x 2622 px, 120 Hz Display wit...
1    6.77 inches, 1080 x 2392 px, 120 Hz Display wi...
2           7.6 inches, 1878 x 2670 px, 120 Hz Display
3    6.9 inches, 1320 x 2868 px, 120 Hz Display wit...
4    6.67 inches, 1080 x 2400 px, 120 Hz Display wi...
Name: display, dtype: object

In [218]:
screen_size = df1['display'].str.strip().str.split().str.get(0).astype(float)

In [219]:
df1.insert(21,'screen_size',screen_size)

In [222]:
df1['screen_size'].isnull().sum()

np.int64(0)

In [220]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,ram_capacity,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,12,256,4056 mAh Battery with Fast Charging,4056,0,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",6.30,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,8,256,6500 mAh Battery with 90W Fast Charging,6500,90,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",6.77,50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,12,256,5800 mAh Battery with Fast Charging,5800,0,"7.6 inches, 1878 x 2670 px, 120 Hz Display",7.60,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,12,256,5391 mAh Battery with Fast Charging,5391,0,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",6.90,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,8,128,5000 mAh Battery with 45W Fast Charging,5000,45,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",6.67,50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [237]:
resolution = df1['display'].str.strip().str.split(',').str.get(1).str.split('px').str.get(0).str.strip()

In [238]:
df1.insert(22,'resolution',resolution)

In [241]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,internal_memory,battery,battery_capacity,fast_charging,display,screen_size,resolution,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,256,4056 mAh Battery with Fast Charging,4056,0,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",6.30,1206 x 2622,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,256,6500 mAh Battery with 90W Fast Charging,6500,90,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",6.77,1080 x 2392,50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,256,5800 mAh Battery with Fast Charging,5800,0,"7.6 inches, 1878 x 2670 px, 120 Hz Display",7.60,1878 x 2670,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,256,5391 mAh Battery with Fast Charging,5391,0,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",6.90,1320 x 2868,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,128,5000 mAh Battery with 45W Fast Charging,5000,45,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",6.67,1080 x 2400,50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [243]:
df1['resolution'].isnull().sum()

np.int64(0)

In [254]:
refresh_rate = df1['display'].str.strip().str.split(',').str.get(2).str.strip().str.findall(r'\d{2,3}').str.get(0).apply(lambda x: 60 if pd.isna(x) else x).astype(int)

In [255]:
df1.insert(22,'refresh_rate',refresh_rate)

In [256]:
df1.head()

,index,brand_name,model,price,rating,sim,has_5g,has_nfc,has_ir_blaster,processor,...,battery,battery_capacity,fast_charging,display,screen_size,refresh_rate,resolution,camera,card,os
0,2,apple,Apple iPhone 18 Pro,164900,85.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,4056 mAh Battery with Fast Charging,4056,0,"6.3 inches, 1206 x 2622 px, 120 Hz Display wit...",6.30,120,1206 x 2622,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
1,3,vivo,Vivo T4 Pro 5G (8GB RAM + 256GB),29999,72.0,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster",True,False,True,"Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor",...,6500 mAh Battery with 90W Fast Charging,6500,90,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",6.77,120,1080 x 2392,50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,4,apple,Apple iPhone Duo,299900,84.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,5800 mAh Battery with Fast Charging,5800,0,"7.6 inches, 1878 x 2670 px, 120 Hz Display",7.60,120,1878 x 2670,48 MP + 48 MP Dual Rear & 12 MP + Under-displa...,Memory Card Not Supported,None
3,5,apple,Apple iPhone 18 Pro Max,179900,86.0,"Dual Sim, 5G, VoLTE, NFC, eSIM, Wi-Fi",True,True,False,"Apple A20 Pro, Hexa Core Processor",...,5391 mAh Battery with Fast Charging,5391,0,"6.9 inches, 1320 x 2868 px, 120 Hz Display wit...",6.90,120,1320 x 2868,48 MP + 48 MP + 48 MP Triple Rear & 18 MP Fron...,Memory Card Not Supported,iOS v27
4,6,realme,Realme P1 5G (8GB RAM+ 128GB),14999,58.0,"Dual Sim, 5G, VoLTE, Wi-Fi",True,False,False,"Dimensity 7050, Octa Core, 2.6 GHz Processor",...,5000 mAh Battery with 45W Fast Charging,5000,45,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",6.67,120,1080 x 2400,50 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v14

In [257]:
# Working on camera column